### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by osilkin98** [orbitdb/orbitdb#1001]
HI,

It doesn't look like there's support for this yet and I didn't see any issues about it, but it'd be awesome to get support for OrbitDB in Deno.

**Comment by tabcat** [comment]
what is needed to support deno? open to accepting PRs for this. If esm is necessary, that is being worked on and should arrive in july.

**Comment by osilkin98** [comment]
@tabcat Good question. I haven't tried running this, but I believe Deno uses different APIs than Node. I'll have to try it out and report back

**Comment by osilkin98** [comment]
@tabcat After attempting to run it locally and inspecting the dependencies, this may be better handled as a separate project altogether. Deno doesn't support `require` and uses URL imports for third-party dependencies instead.

**Comment by haydenyoung** [comment]
Closing. Looks like OP reached their conclusion.

**Comment by jimwhite** [comment]
I'm also interested in running OrbitDB in Deno.  It seems a great fit for a decentralized system.  As @osilkin98 said it doesn't rely on a centralized library like Node npm does.  

How does OrbitDB depend on `require`?  The only place I can find it being used is here:
https://github.com/orbitdb/orbitdb/blob/af55f118fe39424f2bf84e2dec5e042074eb9720/conf/webpack.tests.config.js#L8
https://github.com/orbitdb/orbitdb/blob/af55f118fe39424f2bf84e2dec5e042074eb9720/conf/webpack.tests.config.js#L40
