### ISSUE TITLE
Feature request: Multi-threaded database access

### ISSUE THREAD

**Issue by threshold862543** [orbitdb/orbitdb#1016]
LevelDB and thus the OrbitDB databases can only be accessed by a single process at a time, posing an obstacle for multithread database access:
```
OpenError: IO error: lock ... LOCK: Resource temporarily unavailable
... at .../node_modules/orbit-db-storage-adapter/node_modules/levelup/lib/levelup.js:119:23
```
It would be cool if there was a way to somehow avoid this issue.

**Comment by haadcode** [comment]
Recommended way of usage is one database per thread. Adding multithread support adds a lot of complexity that we don't want to take up on.

You may be able to work something out on the storage level by replacing LevelDB with some other database solution that supports multithreading. See the [Storage documentation](https://github.com/orbitdb/orbitdb/blob/main/docs/STORAGE.md) and [various storage implementations](https://github.com/orbitdb/orbitdb/tree/main/src/storage) for how to create a custom storage solution.
