### ISSUE TITLE
Upgrade leveldown to avoid problems on M1, mobile platforms

### ISSUE THREAD

**Issue by holmesworcester** [orbitdb/orbitdb#1019]
Because OrbitDB uses leveldown 5.x (leveldown is now on 6.x) a patch is required to build OrbitDB on different hardware platforms e.g. mobile. 

See: https://github.com/TryQuiet/quiet/issues/844#issuecomment-1227379574

OrbitDB should upgrade to the latest leveldown. 

(I think leveldown is used in `orbit-db-keystore` and `orbit-db-storage-adapter`. If I should create issues in the respective repositories please let me know.)

**Comment by holmesworcester** [comment]
Update: this also causes problems and requires an annoying workaround for building on M1 Macs, which are supported in later versions of leveldown.

**Comment by haydenyoung** [comment]
Closing as no further information from OP. Feel free to re-open if problems persist.
