### ISSUE TITLE
Feature Request: Simpler address string processing.

### ISSUE THREAD

**Issue by threshold862543** [orbitdb/orbitdb#1020]
Currently, an OrbitDB database object contains an `address` object containing a `root` (the database hash) and a `path` (the database name). It would be nice if there was a simple string or function that contained or returned the "full address" that could easily be passed into other functions. eg. `db.address()` would return
`/orbitdb/QFNnfjnfewjkfnejkfejffjgbuirleghuithwntwhtiu44t3w434/mydbname`.
As it is it seems like you have to manually construct the address from its components, unless I'm missing something.

Alternatively it would be nice if you could pass the address object itself as an argument into `db.open()`.

**Comment by haadcode** [comment]
This has been re-factored in v1.0.0. The addresses are now in the form `/orbitdb/zdpuAmrcSRUhkQcnRQ6p4bphs7DJWGBkqczSGFYynX6moTcDL`. See [Address](https://github.com/orbitdb/orbitdb/blob/main/docs/DATABASES.md#address) documentation.
