### ISSUE TITLE
Support Distributed Search records with elasticlunr.js

### ISSUE THREAD

**Issue by TheRook** [orbitdb/orbitdb#1026]
You could have a key/value collection where the keys have a stand-alone elastic search index.  This would allow clients to fetch the index for a large search or query other clients who have the index with an RPC call to made a search query: 

http://elasticlunr.com/

This would bring scaleable search to distributed applications, after the index is built then it is much cheaper and faster to process search requests on a dataset.

**Comment by marcus-pousette** [comment]
You can modify the [Document store](https://github.com/orbitdb/orbit-db-docstore) to start an elasticsearch instance during the initalization step and use the ipfs client to access the libp2p pubsub and do a RPC like behaviour with all the peers that are subscribing to the store topic. 

I have achieved this [here](https://github.com/dao-xyz/peerbit/tree/master/packages/programs/data/document) (though this is not OrbitDB anymore but a fork I am working on). 

About the search engine, ES is good, but I am very curious when [tantivy](https://github.com/quickwit-oss/tantivy) can be compiled with WASM

**Comment by TheRook** [comment]
peerbit is awesome. In terms of tantivy vs lunr.js it comes down to limitations.  Being pure javascript has its advantages. It works well on arm and x86, there isn't a penalty for being compiled for the wrong one.  The elasticlunr library has the full-text search features and works well cross-platform, so it can work in the browser, in a client or as an RPC node.

If you are building a product search, a form search or newsgroups - then elasticlunr over an RPC can do this. 


> About the search engine, ES is good, but I am very curious when [tantivy](https://github.com/quickwit-oss/tantivy) can be compiled with WASM

**Comment by marcus-pousette** [comment]
> peerbit is awesome. In terms of tantivy vs lunr.js it comes down to limitations. Being pure javascript has its advantages. It works well on arm and x86, there isn't a penalty for being compiled for the wrong one. The elasticlunr library has the full-text search features and works well cross-platform, so it can work in the browser, in a client or as an RPC node.
> 
> If you are building a product search, a form search or newsgroups - then elasticlunr over an RPC can do this.
> 
> > About the search engine, ES is good, but I am very curious when [tantivy](https://github.com/quickwit-oss/tantivy) can be compiled with WASM

That is true, thats a benefit. Though, my experience in working with search engine libs in GC languages in a big data production setting is that the unpredictable heap usage forces you to spend a lot more resources than necessary in many cases. I did rewrite a full text search engine from [Node to Rust and WASMsd it back to js](https://github.com/quantleaf/probly-search) and the performance gains were massive (if I remember correctly) (3x faster insertion times, and significantly less ram usage idling). Perhaps elasticlunr is faster out of the box, but that experience has affected my mindset a little bit regarding how to reason about the WASM usecase for performance critical things

**Comment by haadcode** [comment]
Would be very cool to have a "elasticlunr" database for OrbitDB! You could implement it following the [KeyValue-Indexed](https://github.com/orbitdb/orbitdb/blob/main/src/databases/keyvalue-indexed.js) database model and use elasticlunr in place of Level.

Let us know if you implement this!
