### ISSUE TITLE
Data consistency with malicious peers

### ISSUE THREAD

**Issue by TheRook** [orbitdb/orbitdb#1032]
A Merkle-CRDT is a source for a logical clock that can give a CRDT like orbit additional security guarantees about the data state.  A Merkel-CRDT can be used to make it hard to deny that data was ever seen and provides some source of truth without a full blockchain:
https://research.protocol.ai/publications/merkle-crdts-merkle-dags-meet-crdts/psaras2020.pdf

A Merkle-CRDT using libp2p:
https://github.com/ipfs/go-ds-crdt

Additional security guarantees can prevent complex apps from being abused by malicious orbitdb peers.

**Comment by thinkcucumber** [comment]
Is this a question?

**Comment by haadcode** [comment]
> "why isn't there a way to remove malicious peer from a collection?" 

You can use the [OrbitDBAccessController](https://api.orbitdb.org/module-AccessControllers.AccessControllers-OrbitDB.html) to allow for "removing access for peers".

> Can you please implement a key rotation system?

No, and this isn't the solution for the above concerns. If you're using encryption keys to encrypt your data, key rotation is something to be handled on the application level.
