### ISSUE TITLE
Data is not persistent

### ISSUE THREAD

**Issue by justaluckyguy** [orbitdb/orbitdb#1035]
`import { create } from "ipfs-http-client";
import OrbitDB from "orbit-db";

const client = create();

(async function() {
  const orbitdb = await OrbitDB.createInstance(client);
  const db = await orbitdb.docs("orbit.test.soil.data");
  console.log(db.address.toString());
  await db.put({_id: 1, name:"dev01", soild_data:"XXXX"});
  await db.put({_id: 2, name:"dev01", soild_data:"XXXX"});
  await db.put({_id: 3, name:"dev01", soild_data:"XXXX"});
  await db.put({_id: 4, name:"dev01", soild_data:"XXXX"});

  console.log(db.get(""));
})();
`
Once the execution is finished, I launch the code again to access the database I created, and notice that the data is missing

**Comment by julienmalard** [comment]
Is this in Node or browser?

**Comment by julienmalard** [comment]
And do you succeed in getting the data on the first run, before closing the database?

**Comment by anarkrypto** [comment]
On node the data is saved in you disk (orbit-db folder), on browser it's saved on IndexedDB.

When restarting the db you should be able to see the saved data again.
Except in cases of deploying the script with node.js in environments without persistent storage, such as Heroku.

**Comment by haadcode** [comment]
To make sure your orbitdb *identity* is persistent across re-starts, pass in an `id: "some id or username""` to `createOrbitDB({ id: "some id or username" })`. OrbitDB will generate a random id if one is not passed which then means that it looks for the (previously persisted) data from another directory (and can't find it).
