### ISSUE TITLE
How to run orbit-db daemon?

### ISSUE THREAD

**Issue by hemangjoshi37a** [orbitdb/orbitdb#1056]
There is no documentation about how to run orbit-db daemon. It will be very helpful if anyone could share any information about this.

**Comment by bitcoinbrisbane** [comment]
This article https://medium.com/coinmonks/orbitdb-a-peer-to-peer-database-for-the-decentralized-web-30bac1d056fe suggests `npm run examples:node` but there is no example folders.  Related #1096

**Comment by haadcode** [comment]
We don't have a separate daemon for orbitdb atm. Would be happy to have one through community contributions!

Note that the article linked above is for pre-1.0.0 versions and is not up to date anymore.
