### ISSUE TITLE
IPFS has no export default

### ISSUE THREAD

**Issue by erhard** [orbitdb/orbitdb#1058]
I use vite in es2020 mode and vuejs (quasar) . I can install orbit-db now . But I get an error when I try to run it

SyntaxError: The requested module '/node_modules/.q-cache/vite/spa/deps/ipfs.js?v=c0a32137' does not provide an export named 'default'

**Comment by anarkrypto** [comment]
Try ```import * as IPFS from 'ipfs'```;

**Comment by philBrown** [comment]
The documentation here seems out-of-date or just incorrect.

See https://github.com/ipfs/js-ipfs#install-as-an-application-developer

```shell
$ npm install ipfs-core
```
```js
import * as IPFS from 'ipfs-core'
```

**Comment by haydenyoung** [comment]
Closing as looks to be answered.
