### ISSUE TITLE
Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by anarkrypto** [orbitdb/orbitdb#1060]
Hi,

I've created a chat with orbit-db and react/next.js

After users sign in with their keys, the browser connects orbit to the IPFS node and start sending the messages into a 'feed' database.

The chat works fine, messages arrive quickly enough. Until suddenly the console shows the following 
error:

Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR

![image](https://user-images.githubusercontent.com/32111208/216749494-b6993f5c-f553-47de-ae6e-c90ad3f1db25.png)

After that the communication is interrupted, the messages do not arrive.

Reverse-proxy is already configured with HTTP2.
I didn't find solutions to the problem.

 - The chat: https://github.com/apptalktime/p2p-chat
- The node container: https://github.com/apptalktime/ipfs-docker
- The reverse proxy config with NGINX: https://github.com/apptalktime/ipfs-api-reverse-proxy

**Comment by haadcode** [comment]
This is prolly related to the (ipfs) http apis used. They're not used anymore in the latest v1.0.0.
