### ISSUE TITLE
orbit-db v29.0 is not replicating data

### ISSUE THREAD

**Issue by anarkrypto** [orbitdb/orbitdb#1062]
It seems that after the last updates orbit-db is no longer synchronizing data (replicated events).

I created a simple chat for demonstration.
Open the second client in a private tab to avoid using the same identity.

### Current obit version (NOT WORKING):
- Demo: https://simple-orbitdb-chat.vercel.app/
- Code: https://github.com/anarkrypto/simple-orbitdb-chat
- orbit-db v0.29.0

### Previous orbit version (WORKING):
- Demo: https://simple-orbitdb-chat-git-workingdeps-anarkrypto.vercel.app/
- Code: https://github.com/anarkrypto/simple-orbitdb-chat/tree/working_deps
- orbit-db v0.28.7

Note that for the old version to work, however, you must use `multiformats v9.9.0`. It's related in #1023
Just downgrading multiformats using orbit-db v0.29 does not solve.

.
.
.

Demo example (messages does not syncing on orbit-db v0.29):

![image](https://user-images.githubusercontent.com/32111208/216919474-51f8aa80-4253-48c6-8807-f334a17b34f8.png)

I'm using Next.js, to make it easier all the code is in /pages/index.tsx

The remote node has the ports properly open and pubsub activated

**Comment by inspiraluna** [comment]
I updated my code with v0.29.0 too and replication works at least here between two different browsers. It seems you are using one single IPFS node. This could be the reason. Each browser needs a dedicated IPFS node.

**Comment by cchris-org** [comment]
Hi,

I am struggling with the same problem here.

versions:
 orbit-db@0.29.0
 ipfs-http-client@60.0.0
 ipfs daemon (kubo) 0.19.0

I have two computers on the same network with boot nodes connected, and 
**pubsub on both nodes (over cli) works perfectly.**
However, I have tested examples in many ways, but nothing works.
The local database gets updated, but I get no events on the other computer (same network, channel/db).

I have tried the following:

- Tested with different IPFS configurations (access control, etc.)
- Manually connected each node to ensure nodes communicate
- Disabled firewalls
- Tried with older orbit-db version too (didn't work)


Test code on computer A (add data):

```
import { create } from 'ipfs-http-client';
import OrbitDB from 'orbit-db';

async function main() {
    const ipfs = create(new URL('http://127.0.0.1:5001'));
    const orbitdb = await OrbitDB.createInstance(ipfs, { directory: './orbitdb' })
    const db = await orbitdb.log('events')
    await db.load()
    
    setInterval(async () => {
        console.log('Adding entry to db')
        await db.add({ time: new Date().getTime() })
    }, 1000)
  
  }  
  main()
```


Test code on computer B (to check events):

```
import { create } from 'ipfs-http-client';
import OrbitDB from 'orbit-db';

async function main() {
    const ipfs = create(new URL('http://127.0.0.1:5001'));
    const orbitdb = await OrbitDB.createInstance(ipfs, { directory: './orbitdb' })
    const db = await orbitdb.log('events')
    await db.load()  
    console.log('Making db check replica')
    db.events.on('replicated', () => {
      const result = db.iterator({ limit: -1 }).collect().map(e => e.payload.value)
      console.log(result.join('\n'))
    })
  }
main()
```
Any ideas please?

**Comment by haydenyoung** [comment]
Please try with the latest version of OrbitDB. If problems persist, feel free to re-open this issue.
