### ISSUE TITLE
[Research Question] Is OrbitDB suitable for larger JSON documents with frequent read/writes? 

### ISSUE THREAD

**Issue by wmx11** [orbitdb/orbitdb#1063]
Hi,

It's not an issue but I'm searching for a decentralized database solution that would work for my application.
I am expecting at least 500k new entries every month with the numbers potentially growing in the near future. 

Is OrbitDB suitable to handle over a million entries without issues? I want to use OrbitDB to aggregate data from various sources using peers and retrieve that data which could be displayed on my website. 

Also, how well does OrbitDB document storage handle new key: pair values? Assuming that there is no schema for you to declare first.

**Comment by haadcode** [comment]
This should be possible, but we haven't benchmarked nor optimized it yet for the >1M scale. Yu'll have to try it out and see what works and what doesn't.

Feel free to re-open the issue or create new ones if you come across any problems.
