### ISSUE TITLE
Remove dependency on FS based modules.

### ISSUE THREAD

**Issue by saul-jb** [orbitdb/orbitdb#1070]
The code imports `fs` and `path` modules which cannot be used in the browser, is there a way these can be refactored out so that it can more easily be bundled and used in a browser?

I know these modules are shimmed and/or conditionally used based on environment but trying to bundle it with Vue 3 (Webpack 5) it breaks because these modules are not included. If you replace these packages or disable them in the Webpack configuration it breaks other things that use them (`path`) during compile time.

It would be really good to make it as seamless as possible between the browser and node environments like Libp2p and IPFS does.

**Comment by Erudition** [comment]
Hopefully this is done in orbit-db-nextgen with Helia...

**Comment by saul-jb** [comment]
> Hopefully this is done in orbit-db-nextgen with Helia...

Yeah, been working on it:

* https://github.com/orbitdb/orbit-db-nextgen/pull/57
* https://github.com/orbitdb/orbit-db-nextgen/pull/62

**Comment by Erudition** [comment]
Thanks! Any idea why the `fs` shim isn't working for me?

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'mkdirSync')`

Happens on this line, in the browser:
https://github.com/orbitdb/orbit-db-storage-adapter/blob/de44df31324d69a27de506d868cb0a1daeaa65b1/src/index.js#L43

Which is weird because if `fs` is null after all, why would anything after the && even get run?

**Comment by saul-jb** [comment]
> Which is weird because if `fs` is null after all, why would anything after the && even get run?

Yeah, I gave up on the current version because of issues like this and jumped to nextgen and had better luck (but of course I have to put up with it's instability since it is in active development). That line should not be causing issues but what I think what is going on here is that that when webpack compiles this it does a few checks and fails then (even through it would work at compile time).

Your best bet is copying their webpack configuration:
https://github.com/orbitdb/orbit-db/blob/main/conf/webpack.config.js

**Comment by Erudition** [comment]
> That line should not be causing issues
Well, when I remove it, OrbitDb works fine...

I'm not using Webpack, but Vite, which uses Rollup for production builds. I needed to polyfill the node built-ins for OrbitDb/IPFS (can you confirm if NextGen still requires these?) and it works fine in dev and mostly in production except for this one error. The polyfill just sets fs to null, which IIUC is exactly what OrbitDb is checking for anyway.

**Comment by saul-jb** [comment]
Not familiar with Vite, the only thing I can think of is that something in the compilation process is modifying that line or the compilation process that you are using has a false positive error there. I wonder if changing that line to `if (fs != null && fs?.mkdirSync != null)` would change anything.

Nextgen does not need node's `fs`, `path` or `buffer` modules but it does need `events` (I have a PR for that one which you can merge locally if you have issues with it: https://github.com/orbitdb/orbit-db-nextgen/pull/63). Again there might be other issues with the nextgen that might make it unusable for you until they finish it.

**Comment by haadcode** [comment]
´fs´ and ´path´ have been removed in v1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

Feel free to re-open this issue or create a new one if you're still having problems with transpilers.
