### ISSUE TITLE
Could not validate signature

### ISSUE THREAD

**Issue by Dalois-30** [orbitdb/orbitdb#1072]
if (!isValid) throw new Error(`Could not validate signature "${entry.sig}" for entry "${entry.hash}" and key "${publicKey}"`)
                          ^

Error: Could not validate signature "30450221009e7b69fc934415e8c53c9514c96e04fe78c1dd44d063413b7909b2e65b1c6d2a02203a2863ed1aff0d1dadd7f17fd9890b084f172c8a576c9c0c323bedd10b0c8a00" for entry "zdpuB2nkpNtqAK6AJNPGpH38c8EdiWtG7ejHeGa4KNb2TBsRJ" and key "04582ec1a8ddd4bf7566ac57ee1f103dc2c1088231cf613309f2ad1a00336037ecdb244d3d9130b0676105237808e75c6f6944ea4d4ea529e782316e57a9bca667"

I am throwing this error when attempting to retrieve data from OrbitDB in Node.js. It appears that the private key is incorrect. What I do not understand is that I did not change anything. I was able to make requests, but suddenly this error occurred when I tried the same request without modifying anything.

**Comment by haadcode** [comment]
Try it with v1.0.0 and see if you're still experiencing the problem. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

If the issue persists, feel free to re-open the issue.
