### ISSUE TITLE
Preparing for Version 1.0.0

### ISSUE THREAD

**Issue by haydenyoung** [orbitdb/orbitdb#1083]
After considerable effort from both the core developers and community at large, OrbitDB is now making its final steps towards its 1.0.0 release. 

The **OrbitDB Release Candidate** is now available for installation, and it will mark the beginning of our version 1 release cycle, providing developers and implementers with a production-ready peer-to-peer, serverless, distributed database system for decentralized applications.

We invite all community members to test out the current release and provide any feedback, problems, bugs, issues and PRs.

The new package, @orbitdb/core, is now available on npmjs and can be installed using `npm i @orbitdb/core@next`.

**Comment by haydenyoung** [comment]
The following packages are available at npm.js:

[@orbitdb/core](https://www.npmjs.com/package/@orbitdb/core) - The core OrbitDB package
[@orbitdb/identity-provider-did](https://www.npmjs.com/package/@orbitdb/identity-provider-did) - The OrbitDB DID identity provider
[@orbitdb/identity-provider-ethereum](https://www.npmjs.com/package/@orbitdb/identity-provider-ethereum) - The OrbitDB Ethereum identity provider

**Comment by haadcode** [comment]
[OrbitDB 1.0.0](https://www.npmjs.com/package/@orbitdb/core) has been published! 🎉 

See [#819](https://github.com/orbitdb/orbitdb/issues/819#issuecomment-1724853434) for more information,.
