### ISSUE TITLE
How to connect to an IPFS instance running inside a container?

### ISSUE THREAD

**Issue by giant-space-turtle** [orbitdb/orbitdb#1091]
I want to build a simple application by following the [GETTING_STARTED](https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md) guide.

The guide says to first create an IPFS instance, and then to create an OrbitDB instance using the previously created IPFS node, like this:

```js
const ipfs = await create()
const orbitdb = await createOrbitDB({ ipfs })
```

However, I already have an IPFS instance running inside a container, and I would like OrbitDB to use that node instead of creating a new one.

How would I accomplish that? Thank you.

**Comment by haadcode** [comment]
This is not possible. Use an in-process `ipfs` instance as described in the documentation and examples.

In the future, it may be possible to use a separate ipfs process as OrbitDB integrates with [Helia](https://github.com/ipfs/helia).
