### ISSUE TITLE
Dead links in the readme

### ISSUE THREAD

**Issue by thetarnav** [orbitdb/orbitdb#1092]
There are a few links leading to nowhere in the readme:

Helia
![image](https://github.com/orbitdb/orbitdb/assets/24491503/bd5b55e4-ee99-4066-bd86-bb209e72dad1)

Docs
![image](https://github.com/orbitdb/orbitdb/assets/24491503/afbac818-a666-4b15-801b-f30a2ce57d55)

FAQ
![image](https://github.com/orbitdb/orbitdb/assets/24491503/99c3406d-3127-49bf-988c-2acc4da94c45)

**Comment by haydenyoung** [comment]
Thanks for reporting this. Addressed in #1100
