### ISSUE TITLE
Add a .prettierrc file?

### ISSUE THREAD

**Issue by bitcoinbrisbane** [orbitdb/orbitdb#1093]
The project style looks something like this ...

```json
{
	"bracketSpacing": true,
	"endOfLine": "auto",
	"insertPragma": false,
	"printWidth": 80,
	"proseWrap": "preserve",
	"quoteProps": "as-needed",
	"requirePragma": false,
	"semi": false,
	"singleQuote": true,
	"tabWidth": 2,
	"trailingComma": "all",
	"useTabs": true
}
```

**Comment by haadcode** [comment]
Thanks @bitcoinbrisbane but we'd like to keep the tooling minimal, so we won't be adding prettier to the project at this point. For linting, we use [StandardJS](https://github.com/standard/standard).

Closes #1094.
