### ISSUE TITLE
Examples in package.json are invalid

### ISSUE THREAD

**Issue by bitcoinbrisbane** [orbitdb/orbitdb#1096]
Seems the examples folder is removed, however there are still these scripts on the `[package.json](https://github.com/orbitdb/orbitdb/blob/main/package.json)`  

- "examples:events": "node examples/events.js",
- "examples:keyvalue": "node examples/keyvalue.js",
- "examples:browser": "open-cli examples/browser/browser.html",
- "examples:browser-webpack": "open-cli examples/browser/browser-webpack-example/index.html",

**Comment by haadcode** [comment]
This was fixed in https://github.com/orbitdb/orbitdb/pull/1103.
