### ISSUE TITLE
What is the purpose of an Identity having two public keys?

### ISSUE THREAD

**Issue by leblowl** [orbitdb/orbitdb#1117]
At least with the default publickey provider, it looks like an `Identity` consists of two key pairs, where the public parts of the those keys make up the `id` and `publicKey` fields. The private keys of those two sign each other's public key, tying them together, so that `id` can be used for access control. https://github.com/orbitdb/orbitdb/blob/9b8bcb7257bb180b5b013e63b75313d2a2846b38/src/identities/identities.js#L83-L91

What benefit does this approach provide? Why not just use publicKey? Thanks!

**Comment by haydenyoung** [comment]
By having a root or parent key, we can derive child keys from that parent and grant access per db. We grant access to the “root key” which can sign “child keys” and then those “child keys” can write to the db. So whether different dbs are written to by different child keys doesn’t make a difference. The root key is like a “user” and the child keys are “devices”.

**Comment by haydenyoung** [comment]
Marking as answered. If you would like to discuss this concept further with the community, feel free to move the discussion to https://matrix.to/#/#orbitdb_Lobby:gitter.im.
