### ISSUE TITLE
Where should I open potential security issues?

### ISSUE THREAD

**Issue by leblowl** [orbitdb/orbitdb#1118]
It looks like security@orbitdb.org no longer exists. I have an issue I'd like to discuss, but not sure how you'd prefer to discuss it. Thanks!

**Comment by abuvanth** [comment]
it is open source so you can assign CVE ID if a valid security issue is reproducible

**Comment by haadcode** [comment]
Feel free to chat up on matrix, I’m @haad:matrix.org

**Comment by haydenyoung** [comment]
Closing but feel free to reopen if you have any trouble filing your security issue.
