### ISSUE TITLE
orbit-db-nextgen or this?

### ISSUE THREAD

**Issue by benzmuircroft** [orbitdb/orbitdb#1123]
I see that the nextgen version uses pubsub and calls it experimental.

here: https://github.com/orbitdb/orbit-db-nextgen/blob/main/examples/keyvalue.js

That does sound really cool. Does this version use pubsub? because this looks more active.

**Comment by haydenyoung** [comment]
orbit-db-next is marked as "Archived". Please use https://github.com/orbitdb/orbitdb as it is the most up-to-date version of OrbitDB.
