### ISSUE TITLE
can we link data?

### ISSUE THREAD

**Issue by benzmuircroft** [orbitdb/orbitdb#1124]
In a key/value db that uses json can we link to a key value of another key/value db. If so is there an example code for this?

**Comment by haydenyoung** [comment]
For some loose linking you could reference the hash of the other db I guess. We don't have any examples of this but you may find other community members have had similar thoughts. Might be worth asking around in the [OrbitDB lobby](https://matrix.to/#/#orbitdb_Lobby:gitter.im).
