### ISSUE TITLE
why node 20?  

### ISSUE THREAD

**Issue by MichaelJCole** [orbitdb/orbitdb#1151]
The node engine was updated to node v20.  

What features of node v20 does orbit depend on?

https://github.com/orbitdb/orbitdb/blob/ea6bfd93e0a15c5fc70d219b5c09c270196f0841/package.json#L12

I ask because Electron (a cross-platform html app framework with installers and desktop integration) packages node and chrome together.  Electron's node version is 18.  https://releases.electronjs.org/release/v28.1.4

Electron customizes node, so it stays a release behind Node for their own sanity.

Is there some necessary feature of node 20 that Orbitdb requires?  Or will node 18 work as well?

**Comment by haydenyoung** [comment]
OrbitDB should work with 18.

We're discussing whether to change engine.os or remove altogether.

**Comment by haydenyoung** [comment]
> Thanks for the DB.
> 
> Node 18 is in LTS until April 2025: https://nodejs.org/en/about/previous-releases I saw an Electron alpha using node 20. Electron's website says the current version w/ 18 is supported until August 2024.
> 
> By features, ESM packaging would require node 14. By support, LTS would be 18 until 2025. I think electron will move faster than that.
> 
> Thanks again!

Thanks for the info.
