### ISSUE TITLE
Uncaught Error: Could not append entry: although write access is granted

### ISSUE THREAD

**Issue by koh-osug** [orbitdb/orbitdb#1153]
I give write permissions to all identities when creating the database:

~~~javascript
 const identities = await Identities({ path: `./orbitdb/test/identities` })
  const id = "test"
  const identity = identities.createIdentity({ id })
  orbitdb = await createOrbitDB({ipfs: ipfs, identities, id: `test`, directory: `./orbitdb/test`})
 db = await orbitdb.open("test",
      {type: 'documents',
        AccessController: OrbitDBAccessController({ write: [orbitdb.identity.id, '*']})})
~~~

In the other peer I connect with:

~~~javascript
 db = await orbitdb.open(dbAddress,
      {type: 'documents'})
~~~

Still when the other peer connects the append operation fails with:

> Uncaught Error: Could not append entry

In `identities.js` I can see that the identity is not found, but since I have specified:

~~~javascript
const getIdentity = async (hash) => {
    const bytes = await storage.get(hash)
~~~

What is wrong with the write permission how I use it?

**Comment by haydenyoung** [comment]
Out of interest, what happens if you change the above write to:

```
db = await orbitdb.open("test",
      {type: 'documents',
        AccessController: OrbitDBAccessController({ write: ['*']})})
```

**Comment by koh-osug** [comment]
Does not make a difference. In `canAppend` my other peer is always checking `await identities.getIdentity(entry.identity)` and does not find the identity. I assume this identity is only in the creating nodes local identities DB and the syncing node does not have it.

~~~javascript
  const canAppend = async (entry) => {
    const writerIdentity = await identities.getIdentity(entry.identity)
    if (!writerIdentity) {
      return false
    }

    const { id } = writerIdentity
    // If the ACL contains the writer's public key or it contains '*'
    const hasWriteAccess = await hasCapability('write', id) || await hasCapability('admin', id)
    if (hasWriteAccess) {
      return identities.verifyIdentity(writerIdentity)
    }

    return false
  }
~~~

**Comment by haydenyoung** [comment]
Pass ipfs to your identities function so that peer1 can get peer2's identity hash from its identity store.

```
 const identities = await Identities({ ipfs, path: `./orbitdb/test/identities` })
``` 

When canAppend checks the entry's identity, if it isn't available locally, it will try and retrieve it from the other peer. using IPFS:

```
const canAppend = async (entry) => {
  const writerIdentity = await identities.getIdentity(entry.identity) // <-- getIdentity will query IPFS for the other peer's identity. 
```

**Comment by koh-osug** [comment]
Thanks. I will try this. Is the [documentation](https://github.com/orbitdb/orbitdb/blob/main/docs/ACCESS_CONTROLLERS.md) in sync with this recommendation? There the code snippet is:

~~~go
const identities = await Identities()
const anotherIdentity = identities.createIdentity('userB')

const db = orbitdb.open('my-db', { AccessController: OrbitDBAccessController({ write: [orbitdb.identity.id, anotherIdentity.id]) })
~~~

In my case I also pass a `path`, maybe this is the difference.

**Comment by koh-osug** [comment]
The fix works. Great. So, is a fix to the ACCESS_CONTROLLER doc needed? I can create a pull request or you can fix it, whatever you prefer.

**Comment by haydenyoung** [comment]
PRs are always welcome. Feel free to capture your thoughts in a PR and I will take a look.

**Comment by koh-osug** [comment]
> PRs are always welcome. Feel free to capture your thoughts in a PR and I will take a look.

Done so. Not sure if the ipfs argument could also be necessary for the IPFSAccessController.
