### ISSUE TITLE
TS7016: Could not find a declaration file for module @orbitdb/core.

### ISSUE THREAD

**Issue by sheiy** [orbitdb/orbitdb#1157]
<img width="1056" alt="image" src="https://github.com/orbitdb/orbitdb/assets/12210038/a33d55d8-eb71-41fc-959f-45212045948e">

**Comment by julienmalard** [comment]
In the absence of official TypeScript types so far, you could use unofficial types such as https://github.com/reseau-constellation/orbit-db-types/.

**Comment by haydenyoung** [comment]
Closing as answered.
