### ISSUE TITLE
Sync only to N entries.

### ISSUE THREAD

**Issue by sleep9** [orbitdb/orbitdb#1167]
This is more of a feature request than a bug...
Is there a way that the oplog "events" can sync only to the latest N entries to keep nodes performant?
Just getting acquainted with some of the code and this sprung to mind.

**Comment by haydenyoung** [comment]
An OrbitDb peer would require all oplog entries in order to successfully build the database. This is due to the way in which the order of entries is determined (I.e. using a logical clock).
