### ISSUE TITLE
Altering protection to prevent changing data of other users

### ISSUE THREAD

**Issue by mete828670** [orbitdb/orbitdb#1179]
Hello Dear OrbitDB Team,

I want to create a system that has a register/log-in mechanism using IPFS and OrbitDB. The software I am going to build is intended to write username-password into OrbitDB database. Since OrbitDB is decentralized, the data is going to be accessible and changed by others. I know that there is an "Access Control" mechanism. However, everyone needs to have a write permission to register and for other database operations and this permission causes anyone to change other people's password.

I need anyone to be able to create a new data but everyone can alter only the data that was created by them. Is it possible to apply a method for this purpose in OrbitDB? If not, what do you think about building a feature like this?

Thank you so much.

**Comment by haydenyoung** [comment]
My suggestion would be to create a database for each user. This would ensure only the user can edit their own data. 

However, if you have a use case which requires adding user details to a single database, you could develop [a custom access controller](https://github.com/orbitdb/orbitdb/blob/main/docs/ACCESS_CONTROLLERS.md#custom-access-controller) which checks the user's public key against the entry being edited.

Please be aware that the data you are storing to OrbitDB is in clear text unless you are explicitly encrypting it yourself.

**Comment by mete828670** [comment]
I think I will try custom access controller function. I didn't know this feature. Thank you so much.
