### ISSUE TITLE
Code Sample Issues in OrbitDB Documentation for Access Controllers

### ISSUE THREAD

**Issue by orwithout** [orbitdb/orbitdb#1182]
I encountered several issues while following the example code in the [Access Controllers section](https://github.com/orbitdb/orbitdb/blob/main/docs/ACCESS_CONTROLLERS.md#:~:text=of%20the%20database.-,OrbitDB%20Access%20Controller,-The%20OrbitDB%20access) of the OrbitDB documentation. Here's the problematic part of the code snippet as found in the documentation:

![image](https://github.com/orbitdb/orbitdb/assets/19142891/05448da9-45c5-4009-a05d-611cbc7b26b0)

The example code includes an import statement:
```javascript
import { Libp2pOptions } from './config/libp2p.js'
```
which appears to reference a local module configuration. Upon revisiting the documentation on the Helia project's GitHub page at [Helia's GitHub](https://github.com/ipfs/helia#:~:text=%27%40helia/strings%27-,const%20helia%20%3D%20await%20createHelia(),-const%20s%20%3D), I noticed that we could directly use
```javascript
const orbitdb = await createOrbitDB()
```
to create a node instead. After making this adjustment, I was able to run the example code. However, I encountered some errors in the browser's console as follows:
![image](https://github.com/orbitdb/orbitdb/assets/19142891/b8a6dd57-f60c-43c8-80c2-07e8e841e96f)
Error log text:
```log
test_odb_id.js:16  Uncaught TypeError: Cannot read properties of undefined (reading 'grant')
    at test_odb_id.js:16:11
(anonymous) @ test_odb_id.js:16
IndexedDB (async)
_open @ index.js:77
open @ abstract-level.js:153
LevelStorage @ level.js:30
KeyStore @ key-store.js:126
await in KeyStore (async)
Identities @ identities.js:40
(anonymous) @ test_odb_id.js:11
Show 5 more frames
Show less

identities.js:73  Uncaught (in promise) TypeError: Cannot create property 'keystore' on string 'userB'
    at Object.createIdentity (identities.js:73:13)
    at test_odb_id.js:12:36
createIdentity @ identities.js:73
(anonymous) @ test_odb_id.js:12
Show 1 more frame
Show less

index.js:64  Uncaught (in promise) Error: `undefined` is not supported by the IPLD Data Model and cannot be encoded
    at undefinedEncoder (index.js:64:9)
    at objectToTokens (encode.js:289:20)
    at Array (encode.js:228:22)
    at objectToTokens (encode.js:289:20)
    at Object (encode.js:262:9)
    at objectToTokens (encode.js:298:10)
    at encodeCustom (encode.js:430:18)
    at encode (encode.js:461:10)
    at Object.encode2 (index.js:140:39)
    at encode (block.js:181:23)
```

### Environment
- Browser Version: Google Chrome 123.0.6312, Microsoft Edge 123.2420
- Operating System: Windows 2022
- `helia` Version: 4.2.1
- `@Orbitdb/core` Version: 2.2.0

### Code Source to Run
html:
```html
<!-- odb_test.html -->
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body>
    <h2>ODB Test</h2>
    <script type="module" crossorigin src="./odb_test.js"></script>
</body>
</html>
```
javascritp:
```javascritp
// odb_test.js
import { createLibp2p } from 'libp2p';
import { createHelia } from 'helia';
import { LevelBlockstore } from 'blockstore-level';
import { createOrbitDB, Identities, OrbitDBAccessController } from '@orbitdb/core';
// import { Libp2pOptions } from './config/libp2p.js'

// const blockstore = new LevelBlockstore('./ipfs')  //This line was not used in the original text
// const libp2p = await createLibp2p(Libp2pOptions)
// const ipfs = await createHelia({ libp2p })
const ipfs = await createHelia();

const orbitdb = await createOrbitDB({ ipfs });

const identities = await Identities({ ipfs });
const anotherIdentity = identities.createIdentity('userB');

const db = orbitdb.open('my-db', { AccessController: OrbitDBAccessController({ write: [orbitdb.identity.id, anotherIdentity.id]})}); // This line in the original text is missing a closing `}`

db.access.grant('write', anotherIdentity.id);
// db.access.revoke('write', anotherIdentity.id)
console.log('access.type:',db.access.type);
console.log('access.write',db.access.write);
```

**Comment by haydenyoung** [comment]
Thanks for bringing this to our attention as this is not entirely clear. 

./config/libp2p.js is Libp2p configuration which you create and then import into your OrbitDB implementation. See [this section](https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md#libp2p) for an explanation of what ./config/libp2p.js entails.

We'll try and update the documentation to be clearer.

If the problem persists, please add a comment to this issue.

**Comment by orwithout** [comment]
Thank you for your response. It seems the configuration provided is for a Node.js environment:
![image](https://github.com/orbitdb/orbitdb/assets/19142891/8d629e58-f563-443c-a389-fc321dba0b43)
However, I am trying to run this in a browser environment and follow the example to add users and configure permissions. Despite adapting the configuration to be browser-compatible, I still encounter the error "Unable to create UserB". Could you provide a complete configuration example for the browser environment? Thank you.

**Comment by haydenyoung** [comment]
> Thank you for your response. It seems the configuration provided is for a Node.js environment: ![image](https://private-user-images.githubusercontent.com/19142891/331883594-8d629e58-f563-443c-a389-fc321dba0b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDUxNDksIm5iZiI6MTcyMTc0NDg0OSwicGF0aCI6Ii8xOTE0Mjg5MS8zMzE4ODM1OTQtOGQ2MjllNTgtZjU2My00NDNjLWEzODktZmMzMjFkYmEwYjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE0MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMTY3YjQwNDZhNGQ0ZGNhYWNiYmNhMzdhMTA1MzIyZGJlMmRhNjE2YTlmYjU4MzQ1Y2ZiYWY3ZjcxYjhmZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qI1ETBi1YkYXDraTh9DuZsBpqZ_WeV96nsgiK4fC09M) However, I am trying to run this in a browser environment and follow the example to add users and configure permissions. Despite adapting the configuration to be browser-compatible, I still encounter the error `"Cannot create property 'keystore' on string 'userB'"`. If you could provide a complete configuration example for the browser environment, I would greatly appreciate it. Thank you.

Okay my understanding is:

- You have a browser peer (browser1) running OrbitDB. You want to create a db (let's call it db1) here,
- You run a second browser peer (browser2) where you would like to replicate db1 in your second browser peer,
- You would like to add browser2's identity to db1's access controls so that browser2 can write to the db?

The issue you would like to resolve is the access control for browser1?

**Comment by orwithout** [comment]
Yes, this is indeed the ultimate goal I want to achieve. On the way to this goal, I encountered challenges as demonstrated in this issue.

**Comment by haydenyoung** [comment]
Does the database replicate if you allow blanket write access? 

E.g.

```
db = await orbitdb.open('my-db', { AccessController: IPFSAccessController({ write: ['*'] }) })
```

If this works, can you then try the same with OrbitDBAccessController?

```
db = orbitdb.open('my-db', { AccessController: OrbitDBAccessController({ write: ['*']})});
```

Also, in regards to the error "Cannot create property 'keystore' on string 'userB'", is there any more information you can provide? Stacktrace, etc?

**Comment by haydenyoung** [comment]
Closing as inactive. If you are able to confirm universal write access, please re-open and provide any findings.
