### ISSUE TITLE
issue trying to get multiple nodejs peers to sync

### ISSUE THREAD

**Issue by endomorphosis** [orbitdb/orbitdb#1183]
I was working on trying to use orbitdb to shard and serve a K nearest neighbors search engine using orbitdb as the key:value store, with the math part being handled by FAISS, and try to benchmark whether or not it is feasible with 8 million records in chunks of 4096 key-value pairs. 

I have two nodes working on the local area network, and I've tried to throw the kitchen sink of different networking and peer discovery methods, but I cant seem to get the two different nodes to talk to each other on different PCs.

code
https://github.com/endomorphosis/orbitdb-benchmark/blob/master/src/orbitv3-slave-swarm.js
https://github.com/endomorphosis/orbitdb-benchmark/blob/master/src/orbitv3-master-swarm.js

node /home/devel/orbitdb-benchmark/src/orbitv3-master-swarm.js --ipAddress=127.0.0.1 --port=60001 --swarmName=caselaw --chunkSize=8 --index=1
node /home/barberb/orbitdb-benchmark-1/src/orbitv3-slave-swarm.js --ipAddress=127.0.0.1 --port=50001 --swarmName=caselaw --chunkSize=8 --index=1

**Comment by haydenyoung** [comment]
Are the 2 pcs on the same local network?

**Comment by endomorphosis** [comment]
yes

**Comment by haydenyoung** [comment]
Have you tried using mdns for peer discovery? If not, try to configure it in the you Libp2p settings for Helia, E.g.

```
import { mdns } from '@libp2p/mdns'

export default {
  peerDiscovery: [
    mdns()
  ],
  /* other settings */
}
```
This should allow peers to discover one another on the local network without explicitly dialling one another.

**Comment by endomorphosis** [comment]
> Have you tried using mdns for peer discovery? If not, try to configure it in the you Libp2p settings for Helia, E.g.
> 
> ```
> import { mdns } from '@libp2p/mdns'
> 
> export default {
>   peerDiscovery: [
>     mdns()
>   ],
>   /* other settings */
> }
> ```
> 
> This should allow peers to discover one another on the local network without explicitly dialling one another.

https://github.com/endomorphosis/orbitdb-benchmark/blob/master/src/orbitv3-master-swarm.js#L63

**Comment by haydenyoung** [comment]
I've tried launching the peers in the above example and they are able to find one another. Using a simple peer:connect confirms this:

```
ipfs.libp2p.addEventListener("peer:connect", event => {
    console.log('connected', event.detail)
})
```

Can you dial master from slave explicitly?

I.e.

```
await ipfs.libp2p.dial(multiaddr(masterAddress))
```

If the problem persists, [Libp2p may be better able to guide you](https://filecoinproject.slack.com/archives/C046HDAHA13) in getting the peers to communicate.

**Comment by haydenyoung** [comment]
Closing as stale. Feel free to reopen if you have more information to share.
