### ISSUE TITLE
In GETTINGSTARTED.md there is a typo in the code directions, extra space after documents

### ISSUE THREAD

**Issue by crystal-koii** [orbitdb/orbitdb#1191]
In GETTINGSTARTED.md there is a typo in the code directions, extra space after documents:

```const db = await orbitdb.open('my-documents-db', { type: 'documents '})```

should be:

```const db = await orbitdb.open('my-documents-db', { type: 'documents'})```

**Comment by haydenyoung** [comment]
Thanks for reporting this issue. We will address shortly. Alternatively, feel free to submit a PR.
