### ISSUE TITLE
Vector & Graph capabilities

### ISSUE THREAD

**Issue by surapuramakhil** [orbitdb/orbitdb#1203]
Reqeust for capabilities 

- Text Search capabilities like open Search / Elastic Search
- Vector Search / Store capabilities - ANN search

**Comment by haydenyoung** [comment]
Thanks for the suggestions. 

Additionally, if these are areas you are knowledgeable about, we welcome improvements as PRs also.

**Comment by haydenyoung** [comment]
Closing but please feel free to submit a PR. Alternatively, OrbitDB is modular. You could build a module and load it via OrbitDB's configuration if required.

**Comment by surapuramakhil** [comment]
> Closing but please feel free to submit a PR. Alternatively, OrbitDB is modular. You could build a module and load it via OrbitDB's configuration if required.

Hey @haydenyoung I would suggest letting it open. I am a DB user, never built any DB's from scratch / not skilled in writing DB code.

closing this indicates - request has been denied.

There are two things you can do.
- request I have requested, "open Source DBs" have those functionality - "Elastic Search - for text, a lot on vector search". You can use that code to achieve this functionality.
- or keep this request open - whenever any contributors of those projects see this, they might raise a PR.

**Comment by haydenyoung** [comment]
@surapuramakhil We would like to keep issues focussed on specific bugs and updates to the OrbitDB code base which can be resolved and closed.

Instead, we have opened up Github Discussions for general conversation about OrbitDB. Would you like to propose your request under [Ideas](https://github.com/orbitdb/orbitdb/discussions/new?category=ideas)?

Thanks
