### ISSUE TITLE
give option for use customStorage for key-store.

### ISSUE THREAD

**Issue by abuvanth** [orbitdb/orbitdb#1211]
key-store using leveldb (indexDB api not available in react native) which is not supported in react native.
if there is option to use customStorage in key-store. we can use alternative (async-storage) db for leveldb in react native.

proposed feature

```javascript
const keyStorage = CustomKeyStorage()
  const orbitdb = await createOrbitDB({ ipfs, keyStorage })
```

**Comment by abuvanth** [comment]
i can see keyStore accept storage parameter here - https://github.com/orbitdb/orbitdb/blob/4fccfda975d607a14d67d36714871d7c300781d4/src/key-store.js#L118

but storage parameter not given in https://github.com/orbitdb/orbitdb/blob/4fccfda975d607a14d67d36714871d7c300781d4/src/orbitdb.js#L52

**Comment by haydenyoung** [comment]
You can pass a custom keystore to identities and then pass your custom identities to createOrbitDB.

https://github.com/orbitdb/orbitdb/blob/main/docs/IDENTITIES.md#specifying-a-keystore.

**Comment by abuvanth** [comment]
thanks. i got answer, hence closed
