### ISSUE TITLE
Trouble running install command with Windows 10 operating system

### ISSUE THREAD

**Issue by wthompson40** [orbitdb/orbitdb#125]
Currently trying to get the browser examples to work, but cannot get past the "npm install" command on my Windows 10 system.  Below is the error output received.  Any advice and feedback appreciated and thank you in advance.

---

C:\Users\Will\orbit-db>npm install

> go-ipfs-dep@0.4.4-floodsub2 install C:\Users\Will\orbit-db\node_modules\go-ipfs-dep
> node src/bin.js $TARGET_OS

C:\Users\Will\orbit-db\node_modules\go-ipfs-dep\src\index.js:42
        throw new Error('no binary available for os:' + goenv.GOOS)
        ^

Error: no binary available for os:windows
    at checkPlatform (C:\Users\Will\orbit-db\node_modules\go-ipfs-dep\src\index.js:42:15)
    at module.exports (C:\Users\Will\orbit-db\node_modules\go-ipfs-dep\src\index.js:11:3)
    at Object.<anonymous> (C:\Users\Will\orbit-db\node_modules\go-ipfs-dep\src\bin.js:3:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Will\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! go-ipfs-dep@0.4.4-floodsub2 install: `node src/bin.js $TARGET_OS`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the go-ipfs-dep@0.4.4-floodsub2 install script 'node src/bin.js $TARGET_OS'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the go-ipfs-dep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/bin.js $TARGET_OS
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs go-ipfs-dep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls go-ipfs-dep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Will\orbit-db\npm-debug.log

.

**Comment by haadcode** [comment]
Some news here. Windows support was merged to go-ipfs-dep (which is what download the IPFS binary) in https://github.com/diasdavid/go-ipfs-dep/pull/9. I haven't merged this yet to the fork of go-ipfs-dep I use, but will hopefully get to do it soon.

**Comment by haydenyoung** [comment]
Closing as issue may not be experienced with newer versions of libs. Please re-open if problems persist.
