### ISSUE TITLE
libstdc++ error

### ISSUE THREAD

**Issue by nezzard** [orbitdb/orbitdb#210]
How can i install on centos 6?
When i try start app, i get Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/admin/ipfs-node/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v48-linux-x64/wrtc.node)

**Comment by haadcode** [comment]
Hi @nezzard, sorry it took so long to get back to this. Would you mind trying again with the latest version? We've made a lot of progress since March and this may be already fixed.

**Comment by haydenyoung** [comment]
Closing as no further feedback provided. If problems persist, please feel free to re-open or start a new issue.
