### ISSUE TITLE
Set CRDT database

### ISSUE THREAD

**Issue by cristiano-belloni** [orbitdb/orbitdb#249]
Discussing on IRC about the possibility of implementing a "like" functionality:

```
<haad>  when you need something to be unique (ie. only once) but don't need them ordered, one could use a G(row only)-Set CRDT
<haad>  that's actually a nice use case for a "set" database type, we should implement that in OrbitDB (db = orbitdb.setdb('name'))
```

(Here's [the definition of G-Set CRDTs](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type#G-Set_.28Grow-only_Set.29), for reference).

A couple of questions:

- Will it be possible to "count" the elements in G-Sets in O(1)? I mean, a G-Set would probably be a chain of "records" where the last one links to the previous and so on. Would it be possible to store the count along with the data structure? That would mean possibly only fetching the last record?

- I guess it won't be possible to "unlike" after liking, because it's a grow-only data structure. Would there be a way to emulate unliking? Having another set for unlikes wouldn't work, because operations on it would be allowed only if (and after) liking.

**Comment by cristiano-belloni** [comment]
[A LWW-Element-Set](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type#LWW-Element-Set_.28Last-Write-Wins-Element-Set.29) is probably what we want for liking / unliking :)

> LWW-Element-Set (Last-Write-Wins-Element-Set)[edit]
LWW-Element-Set is similar to 2P-Set in that it consists of an "add set" and a "remove set", with a timestamp for each element. Elements are added to an LWW-Element-Set by inserting the element into the add set, with a timestamp. Elements are removed from the LWW-ELement-Set by being added to the remove set, again with a timestamp. An element is a member of the LWW-Element-Set if it is in the add set, and either not in the remove set, or in the remove set but with an earlier timestamp than the latest timestamp in the add set. Merging two replicas of the LWW-Element-Set consists of taking the union of the add sets and the union of the remove sets. When timestamps are equal, the "bias" of the LWW-Element-Set comes into play. A LWW-Element-Set can be biased towards adds or removals. The advantage of LWW-Element-Set over 2P-Set is that, unlike 2P-Set, LWW-Element-Set allows an element to be reinserted after having been removed.[2]

**Comment by haadcode** [comment]
There's now https://github.com/orbitdb/crdts to build this with. It could be introduced as a new database type in OrbitDB, to do that one would need to write a store similar to [eg. KeyValueStore](https://github.com/orbitdb/orbit-db-kvstore).

If anyone wants to contribute this, would be happy to help land a PR!

**Comment by cristiano-belloni** [comment]
That's cool. Thanks!

**Comment by haydenyoung** [comment]
Is this now addressed in the latest release? Closing, but feel free to re-open if further discussion is necessary.
