### ISSUE TITLE
Get in docstore through hash

### ISSUE THREAD

**Issue by osarrouy** [orbitdb/orbitdb#281]
Hi everyone,

I wondered whether there was a way to get a docstore entry through its hash (and not only trough is id).

```
let hash = await db.put({ _id: 'hello world', doc: 'all the things' })
let entry = await db.get(hash)
```
This would be useful to offer an easy IPLD database which would also allow for full text query.

Any idea if this would be feasible ?

Thanks a lot for your work on orbitdb!

**Comment by haadcode** [comment]
This is now possible in 1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

Use the [iterator](https://api.orbitdb.org/module-Databases.Databases-Documents.html) to get `{ hash, record }` from the document database.
