### ISSUE TITLE
OpenError with browser examples

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbitdb#336]
Attempting to run the browser examples on Chrome 64.0.3282.186 on macOS High Sierra throws up a Javascript error on page load, before you even attempt to open a database:

> ipfs.js:2906 Uncaught err {type: "OpenError", name: "OpenError", cause: DOMException: The user denied permission to access the database., message: "The user denied permission to access the database.", stack: "OpenError: The user denied permission to access th…es/orbit-db/examples/browser/lib/ipfs.js:14463:5)"}

After this error, you can enter a database name but the "Open" button will remain disabled.

I can run the same examples correctly from Firefox 58.0.2.

**Comment by ricardojmendez** [comment]
As a follow-up: 

- It does not initialize ipfs on Safari 11.0.3
- It does on Beaker Browser 0.7.11, although on Beaker I cannot connect to the read-only database.

> example.js:192 Error: 'options.create' set to 'false'. If you want to create a database, set 'options.create' to 'true'.
>     at m.open (orbitdb.min.js:1)
>     at openDatabase (example.js:183)
>     at <anonymous>

**Comment by haydenyoung** [comment]
We have reworked a lot of the examples now that we have refactored OrbitDB so these issues may no longer apply. Closing, but feel free to re-open if problems persist.
