### ISSUE TITLE
[help-wanted] benchmarking

### ISSUE THREAD

**Issue by piyushmadan** [orbitdb/orbitdb#348]
I wish to use orbit-db's document store for a project. I am interested to test how read/write speed, latency, query time ( for document store), time to get, time to put, and other key metrics change as the size of database increases.

Is there any benchmarking tool/script previously used? If not, I can contribute.

**Comment by haadcode** [comment]
@piyushmadan would be awesome if we had more benchmarks for OrbitDB! Perhaps you can get started with: https://github.com/orbitdb/orbit-db/tree/master/benchmarks.

**Comment by balupton** [comment]
I have few million json documents, all a few kb in size, totalling a dozen or more GB now.

Use case for me is to be able have them in a semi-realtime database that is public yet p2p so my servers don’t collapse with the demand.

**Comment by haydenyoung** [comment]
There are now a number of benchmarks in https://github.com/orbitdb/orbitdb/tree/main/benchmarks. Please feel free to expand on these and submit your additions as a PR. Additional benchmarks are welcome.
