### ISSUE TITLE
Replicating second store adds data/heads to first store

### ISSUE THREAD

**Issue by maxkerp** [orbitdb/orbitdb#376]
Using: **ipfs-0.29.2.js**, **orbitdb-0.19.7.js**

Hi there,

I'm encountering a bug where if I replicate a second store in the same tab, the data of the second store end up in the first one. Replicating this is fairly easy. I'm using incognito windows of chrome and opera (ipfs doesn't run in firefox incognito).

**Window A**:
After orbit is instantiated I create two docstores and add some values:
```js
orbit.docs('DOCS1', { write: ["*"]}).then((res) => window.db1 = res)
orbit.docs('DOCS2', { write: ["*"]}).then((res) => window.db2 = res)

db1.put({_id: 'db1-1', entry: 1})
db1.put({_id: 'db1-2', entry: 2})
db2.put({_id: 'db2-1', entry: 1})
db2.put({_id: 'db2-2', entry: 2})
``` 
The result is this:
![replication_bug_window_1](https://user-images.githubusercontent.com/4179529/40915491-9084cdb0-67fc-11e8-92d8-01844611a79d.png)

Then I open **Window B** and replicate the two stores:
```javascript
orbit.docs('DOCS1', { write: ["*"]}).then((res) => window.db1 = res)
orbit.docs('DOCS2', { write: ["*"]}).then((res) => window.db2 = res)
```
After replicating `db1` it's how you expect it. It only has the values `db1-1` and `db1-2`. But when I replicate `db2` its values end up in `db1`:
![replication_bug_window_2](https://user-images.githubusercontent.com/4179529/40915623-13797086-67fd-11e8-9daa-28a4ef9d4ffc.png)

I even tried using multiple orbitdb instances or using different directories for the stores. The values of the second replicated store always end up in the first replicated one. To make things worse, if I happen to add to store `db1`  in **Window A**, then the wrong values get send back and merged in **Window B** corrupting all stores with time.

Replicating a **third** store does also add the values to the **first** one.

Any Idea why this could be happening? Maybe something is up with the pupsub module? How are stores differentiated when new heads come in? If needed I can provide full debug output.

**Comment by maxkerp** [comment]
I created a gist to easily replicate the bug. Open two different browsers (I'm using chrome and opera in incognito mode) and run `windowA()` in one and` windowB()` in the other one. I tried different combination of ipfs and orbitdb version and the bug seems to be present in all of them.

https://gist.github.com/maxkerp/8edcb16e0fa86697f338a502a549b5b6#file-orbitdb_replication_bug-html

**Comment by haadcode** [comment]
@maxkerp thanks for digging deep into OrbitDB and discovering new ways it breaks! 😄❤️ (no really, it helps everyone and will help contributors to fix the issues!)

I believe what's happening here is that there's some unwanted parallelism between the [first call](https://gist.github.com/maxkerp/8edcb16e0fa86697f338a502a549b5b6#file-orbitdb_replication_bug-html-L60) to orbitdb.docs() and the [second call](https://gist.github.com/maxkerp/8edcb16e0fa86697f338a502a549b5b6#file-orbitdb_replication_bug-html-L66) and more specifically that second call can happen while the first call is still working, they can happen in different order, etc. and calling orbitdb.docs() in parallel somehow messes up OrbitDB's state internally (a bug we should fix regardless!). Thanks for looking into this and finding it! :)

The correct usage is to wait for the databases to finish their first sequence (createDB1 and createDB2) and only after that call replicateDB1 and replicateDB2. This can be done for example calling the WindowA and B functions with await:
```
await WindowA()
await WindowB()
```

Running the program in that order produces the expected results on my machine. See the code in the comment of the [above gist](https://gist.github.com/maxkerp/8edcb16e0fa86697f338a502a549b5b6#file-orbitdb_replication_bug-html).

@maxkerp let us know if this makes sense and you're able to observe expected results. Like said, that's a bug we should definitely fix (if you're interested to work on a PR to fix it, would be more than happy to help!), but I believe you should be able to progress after applying the above concurrency controls. Hope this helps and if not, happy to answer your questions!

**Comment by maxkerp** [comment]
Thanks a lot for your quick response :heart: :raised_hands: !
I'm getting pretty attached to orbit-db and hope to find time to contribute to it after I'm done with my thesis. So I might start to work on some PRs later this year :smiley: .

Unfortunately this still doesn't fix the issue. Just to be clear, the calls to `WindowA()` and `WindowB()` **must** happen in **different browsers**. If you call `WindowA()` in both Browsers then there is no real purpose of syncing with a remote, since `WindowA()` creates the datasets.

For example calling `WindowA()` in Chrome and `WindowB()` in Firefox/Opera. Cause of this there should be no need to `await WindowA()` and `await WindowB()`. Call `WindowB()` in the BrowserB when `WindowA()` is done in BrowserA. (I should have called them `BrowserA()` and `BrowserB()` :see_no_evil: ).

If you use the code from your comment and only call one in each Browser (B after A) then the values still end up in `db1`. I use the incognito modes of the different browsers to always start with a clean slate and avoid caching issues. Waiting for `load()` in the `replicateX()`-Functions seems to have no effect, I guess because there is no cache.

Concerning the parallelism, I don't actually see any if you only call `WindowB()` in the second Browser. Its `await`ing `replicateDB1` and then `await`ing  `replicateDB2`. So `db1` should be fully `loaded` (and `orbitdb` in idle) before `orbitdb` starts replicating `db2`.

Do I miss something here? :sweat_smile:

**Comment by haydenyoung** [comment]
Is this still the case with the latest version of OrbitDB? Am closing for now but if problems persist, please re-open this issue.
