### ISSUE TITLE
General Public: I want to help contribute!

### ISSUE THREAD

**Issue by 509dave16** [orbitdb/orbitdb#396]
This issue exists for the sole purpose of acting as a place for those who are interested in orbit-db to introduce themselves and find out where they might start helping.

**Comment by RichardLitt** [comment]
Thanks for opening this, @509dave16. I think the best place to introduce yourself may be tomorrow on the community call: see https://github.com/orbitdb/orbit-db/issues/394#issuecomment-403541558. :)

**Comment by haadcode** [comment]
A good way to get started would be to take a look at the open ["Help Wanted" issues](https://github.com/orbitdb/orbit-db/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) and see if there's anything interesting.

In addition, opening PRs for even small issues, improving documentation or just reporting issues you may encounter are all highly appreciated!

**Comment by haydenyoung** [comment]
All help with OrbitDB is welcome. For those interested in contributing, see https://github.com/orbitdb/orbitdb#contributing.
