### ISSUE TITLE
Per-entry permission verification

### ISSUE THREAD

**Issue by coyotespike** [orbitdb/orbitdb#409]
Per-entry permissioning currently is not planned for OrbitDB. But we might be able to accomplish it, using the capabilities approach and the smart contract access controller.

Suppose we store a data structure with roles associated on the blockchain. Concretely, we have a task, with roles associated, like a manager and a worker. 

Suppose we also store the tasks in OrbitDB. Only the manager and worker should be able to edit the task. That is, the roles are defined on chain, and we would like to translate these roles into capabilities.

We could create a new capability per task: write-taskID, with the manager's and owner's keys in the array. In other words, our capabilities would include a lot of things like `{ 'write-<taskId' : [managerKey, workerKey] }`.

The question is where to store and to create these new capabilities. We don't just want to store them directly on chain, as that will cost a lot.

I see two approaches.

- The smart contract ACL uses an Orbit ACL to store capabilities
- The smart contract ACL builds and stores the capabilities itself

**Comment by haydenyoung** [comment]
I think this should now be addressed by both the OrbitDBAccessController and/or a custom AC. I would think a custom controller could be developed with various roles and canAppend could be used to evaluate these roles.

Closing for now as I think the latest AC functionality solves this problem but feel free to re-open if this functionality is still not achievable.
