### ISSUE TITLE
Non-base58 character thrown when creating a new DB eg feed/log/etc

### ISSUE THREAD

**Issue by dirkmc** [orbitdb/orbitdb#419]
I want to use a CID as part of the database name, eg
```javascript
await this.orbitdb.feed('PR-' + url.repoCid + '-' + url.pullCid)
```

This causes `Non-base58 character` to be thrown, because of [this line in orbit-db-address.js](https://github.com/orbitdb/orbit-db/blob/master/src/orbit-db-address.js#L22):
```javascript
const accessControllerHash = parts[0].indexOf('Qm') > -1 ? multihash.fromB58String(parts[0]) : null
```
Should it be
```javascript
const accessControllerHash = address.toString().indexOf('/orbit') === 0 && parts[0].indexOf('Qm') === 0 ? multihash.fromB58String(parts[0]) : null
```

**Comment by haadcode** [comment]
This should be fixed in 1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

If the issue persists, feel free to re-open the issue.
