### ISSUE TITLE
Method to get the latest CID hash of a docstore database object

### ISSUE THREAD

**Issue by tyvdh** [orbitdb/orbitdb#430]
Would love to be able to pass an option to both the query and get methods of docstore to return the latest CID hash of the return object(s).

**Comment by RichardLitt** [comment]
This makes sense to me! PRs would be great for this.

**Comment by haadcode** [comment]
I did something a while ago that may give you this functionality or at least a start for a PR, see https://github.com/orbitdb/orbit-db-docstore/blob/feat/document-revisions/src/DocumentStore.js#L52. Hope this helps.

**Comment by tyvdh** [comment]
@haadcode That works perfectly for my purpose!

The query method works perfectly however whenever I pass an options value to the get method I always get back an empty array.

`glyphdb.get(asset)` => returns array of expected object

`glyphdb.get(asset, {fullOp: true})` => returns empty array
even `glyphdb.get(asset, {})` => returns empty array

If we can sort that out this ticket is as good as closed!

**Comment by tyvdh** [comment]
Ah I see now it's in the `feat/document-revisions` branch. I'll fiddle with it and see if I can get it safely merged into master and running locally. Pretty far behind at this point.

**Comment by haadcode** [comment]
This is possible now. See https://github.com/orbitdb/orbitdb/issues/281#issuecomment-1738643736.
