### ISSUE TITLE
Null hash

### ISSUE THREAD

**Issue by tyvdh** [orbitdb/orbitdb#432]
Doesn't seem to be causing issues, more just curious. Why are my hash values on all my created objects null?

e.g. https://gateway.ipfs.io/api/v0/object/get?arg=QmST1yj556bfQrKqVLY7Sm4cvShEzpjKm2WVgYsKz7dKct

Is that normal? If so what is hash for and is it ever not null?

**Comment by tyvdh** [comment]
![screen shot 2018-08-09 at 12 23 27 pm](https://user-images.githubusercontent.com/4383610/43912020-0979dbec-9bcf-11e8-8be1-f19e58c1c478.png)

**Comment by haadcode** [comment]
That shouldn't have happened :)

But it should be fixed in 1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

If the issue persists, feel free to re-open the issue.
