### ISSUE TITLE
Generalize indexing

### ISSUE THREAD

**Issue by huyhoangio** [orbitdb/orbitdb#437]
Hi guys,

I've been looking at orbitdb code base over the last few weeks. It looks like there is no information about indexes stored in the manifest. Right now only doc-store has indexing, however it only allows indexing on one field. There is no way I can query out the indexed field. If I am an app developer that need to use the data from a particular store, there is no way I can figure out which field(s) were indexed.
As I'm planning on contributing, I have some suggestions:

1. Add a field named `index` in the manifest and `getIndexes()` to the API, this is helpful for developers that need to write app against a particular store. As dynamic permission is on the way, many app makers may share the same database.
2. Multiple indexes on `docstore` and `kvstore`, this is helpful when we want to retrieve information quickly without scanning the whole store. 
3. Possibly allows indexing on `event-log`? For example, if we want to know statistics about a particular activity over a certain period of time, this operation is only one aggregation away versus scanning for the whole `log` then aggregate.

It would be great if we have a discussion here before the community meeting next Tuesday.

**Comment by shamb0t** [comment]
Agreed since otherwise the fields need to be known before-hand

**Comment by haydenyoung** [comment]
Marking as outdated. Please feel free to re-open if this is still something that needs to be addressed in OrbitDB version 1.
