### ISSUE TITLE
Job openings to work on OrbitDB

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbitdb#450]
This issue isn’t about a bug, feature, or a discussion of something new — but I wanted to let the watchers and community here know that **we’re actively looking for hires to come and work on OrbitDB** with us!  
  
This year, we founded Haja Networks, a distributed company looking to grow OrbitDB and related technologies to build a better internet. Haja’s core value is open source; as such, we’re looking to hire people to work directly on OrbitDB. Open source work takes time and effort, and we want to help our community and volunteers be able to spend more time on OrbitDB by funding their work.  
  
This offer is open to anyone, either with a long experience of working with OrbitDB or not. At the moment, we’re hiring full time employees - take a look at our postings on the [Haja Networks open-vacancies repo](https://github.com/hajanetworks/open-vacancies).

Let us know if you have any questions! 

If anyone else is funding or sponsoring to work on OrbitDB, I highly encourage to share the details!

**Comment by huyhoangCSUH** [comment]
No vacancies for part-time?

**Comment by haadcode** [comment]
Closing as obsolete.
