### ISSUE TITLE
Missing documentation `all` in keyvalue store

### ISSUE THREAD

**Issue by oed** [orbitdb/orbitdb#461]
In the [code](https://github.com/orbitdb/orbit-db-kvstore/blob/master/src/KeyValueStore.js#L14) there is an `all` method which returns all entries in the store. However this method is not documented in the API document.

**Comment by RichardLitt** [comment]
I'm having difficulty figuring out which modules are documented in the API guide, too. Are the methods for both https://github.com/orbitdb/orbit-db-docstore and https://github.com/orbitdb/orbit-db-kvstore documented here? What does the `Store` section refer to?

**Comment by haydenyoung** [comment]
This probably no longer applies with latest version of OrbitDB and the associated API docs. Closing for now.
