### ISSUE TITLE
Replication using js-ipfs-api and an ipfs-cluster is not working

### ISSUE THREAD

**Issue by roderik** [orbitdb/orbitdb#473]
I'm building a backend app on orbit-db, and I have set up an ipfs-cluster to ensure that my data stays online forever. The ipfs-cluster works like it should.

So I'm using js-ipfs-api to connect to it and pass that connection into orbit-db like so:

```js
const ipfs = IPFS({ host: '174.138.4.172', port: '9095', protocol: 'http' });
const orbitdb = new OrbitDB(ipfs, `./experiment/orbitdb`);
```

I run some jest tests on them, setting up, storing and retrieving a value, which seems to work.

```js
  test('create and work with a keyvalue store', async () => {
    const keyValue = await orbitdb.keyvalue('testdb.keyvalue');
    // address of the keystore
    keyValueAddress = keyValue.address;
    expect(keyValueAddress.toString()).toBeTruthy();
    // put and get
    await keyValue.put('volume', 100);
    expect(keyValue.get('volume')).toBe(100);
    // close the db
    await keyValue.close();
  });
```

Now during one of these runs, I've printed out the address of the KeyValueStore and I'm now trying the following. This is a test to ensure that in future runs I will actually be able to get my database content back since my nodejs process and disk cache will go away.

As long as I did not delete the local cache from when i made it, this works. When the local cache is deleted, I get back 'undefined' for the volume.

```js
  test('restore and old db by address and work with a keyvalue store', async () => {
    // reload and get
    const keyValueRestore = await orbitdb.keyvalue(
      '/orbitdb/Qmcud9rCZN97s4hfv4fxawWCFLDtW1WZomtfcChzDPjW6H/testdb.keyvalue'
    );
    await keyValueRestore.load();
    expect(keyValueRestore.get('volume')).toBe(100);
    // close the db
    await keyValueRestore.close();
  });
```

The ipfs gateway/api returns something for the address: http://174.138.4.29:9095/api/v0/object/data?arg=Qmcud9rCZN97s4hfv4fxawWCFLDtW1WZomtfcChzDPjW6H

It feels like I'm missing some sort of "sync to node" command?

**Comment by haadcode** [comment]
Closing as obsolete. OrbitDB v1.0.0 doesn't support ipfs http api anymore.
