### ISSUE TITLE
about the access controller

### ISSUE THREAD

**Issue by mccoysc** [orbitdb/orbitdb#476]
by the docs,we know that for changing the access can cause the db address being changed,so now the orbitdb can not support changing access attribute.

maybe you can implements the feature like this:
the 1st way:
save the access informations in database type "feed".and then get and set access attributes from the database,not from the file in ipfs.

the 2nd way:
user give an etherunm smart contract address and get/set access attributes from the smart contract.

**Comment by haadcode** [comment]
@mccoysc that's a great idea! 😄In fact, there's work being done to achieve both: to use an OrbitDB database as an access controller and to be able to use a smart contract as the ACL.

It's not yet quite ready, but hopefully soon. See details in https://github.com/orbitdb/orbit-db/pull/449 (and a very early prototype of the OrbitDB AC in https://github.com/orbitdb/orbit-db/blob/proto/dynamic-access/src/orbit-db-access-controllers/orbitdb-access-controller.js).

**Comment by mccoysc** [comment]
@haadcode what time the new ac  would be ready?

**Comment by haadcode** [comment]
"Soon", but no date set. I would recommend to follow the PR the to stay up to date.

**Comment by lukas2005** [comment]
Hmm, nice! Is the stuff in the PR working but not tested or is it still far away from "Alpha"?

**Comment by haydenyoung** [comment]
Closing as both OrbitDBAccessController and custom ACs should provide this functionality. Feel free to re-open if the latest ACs are not meeting your expectations.
