### ISSUE TITLE
Scalability with Orbit-db

### ISSUE THREAD

**Issue by abh1manyu** [orbitdb/orbitdb#479]
Hi folks, 

I'm just getting started with IPFS and keen to understand best way to get an application up and running. Should I use something like Orbit-db that provides off the shelf schemas? How scalable is the platform right now? 

To be more specific I'm building a simple application that store user public keys, balances and transactions in the IPFS. 

Also, would anyone from the team be interested in discussing the project in more detail? Any help from the community would be appreciated! :)

**Comment by lukas2005** [comment]
While I didn't do much testing myself, based on the stuff that I know about OrbitDB and IPFS I think it should be pretty good at scaling. OrbitDB uses ipfs to store the databases as files and IPFS as a P2P protocol allows you to download the same data from multiple sources. So if you have a lot of data to store this OrbitDB should be a pretty good way to go. You can try writing some stress tests if you want :+1:

**Comment by haydenyoung** [comment]
I would recommend:

1. Benchmark OrbitDB for your needs. We have plans to add more stress-testing to OrbitDB but with limited resources we are addressing other issues first,
2. Looking at LevelDB and js-ipfs/Helia to get a good understanding of how these underlying technologies handle large datasets,
3. Evaluate your datasets and your architecture. Are we talking 1000s, 10s of thousands, millions of records per db?

These are pretty open discussion points. I would recommend [reaching out to other community members](https://matrix.to/#/#orbitdb_Lobby:gitter.im) about their needs and see if they have come across similar limitations.
