### ISSUE TITLE
Database doesn't exist

### ISSUE THREAD

**Issue by rusfearuth** [orbitdb/orbitdb#482]
I don't know what I am doing wrong, but

This is simple source code
```
'use strict';
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const node1 = new IPFS({
  repo: './repo1',
  start: true,
  EXPERIMENTAL: {
    pubsub: true,
  },
})

node1.on('ready', async () => {
  console.log(`Node1 is ready`)

  const orbitdb = new OrbitDB(node1, './orbitdb1')

  const db = await orbitdb.log('events')
  await db.load()

  console.log(db.address.toString())

  await db.add('Test message')
})
```
I got address like `/orbitdb/hash/events`.

Then I used command:

```
$ orbitdb info /orbitdb/hash/events
```
Database /orbitdb/hash/events doesn't exist

I don't know what is wrong with it.

**Comment by haadcode** [comment]
Hi @rusfearuth 👋 

I believe what's happening is that in the code above, the OrbitDB data directory is set to `./orbitdb1` but [`orbitdb` CLI's](https://github.com/orbitdb/orbit-db-cli) default data directory is `./orbitdb` thus the error "Database ... doesn't exist".

Can you try setting the directory in the code above to `./orbitdb` (or leave it out and OrbitDB will default to `./orbitdb`) and see if that helps?

To change the data directory for the CLI (to make it look for the database in `./orbitdb1`), see ["Data directories and paths"](https://github.com/orbitdb/orbit-db-cli#data-directories-and-paths) in the [CLI](https://github.com/orbitdb/orbit-db-cli) documentation.

Hope this helps!

**Comment by rusfearuth** [comment]
I got the next result

```
Error: Key not found in database [/FU/CIQAAQANOXZHWBELVIP6HB3TGN2MT4AKXYMVQNCSD2GO3VGBBSR7FUY]
```

**Comment by foll27** [comment]
> I got the next result
> 
> ```
> Error: Key not found in database [/FU/CIQAAQANOXZHWBELVIP6HB3TGN2MT4AKXYMVQNCSD2GO3VGBBSR7FUY]
> ```

I've got the same issue, after creating a database i try to get info to check all content but when i run the orbitdb info command i got the "key not found in database" error.
Any solution or tip?
Thanks!!

**Comment by haydenyoung** [comment]
Closing as the latest version of OrbitDB along with the new CLI tool should address this. If the problem persists, feel free to re-open.
