### ISSUE TITLE
about replicate

### ISSUE THREAD

**Issue by mccoysc** [orbitdb/orbitdb#484]
as i know,every i add some data to db,the orbitdb would publish a json data to the network which in the following format:
{
....,
next:[
.....
]
}

is really that if i have 100000 records in my database,the 'next' field would be in length 100000?
it's so huge……

**Comment by mccoysc** [comment]
but in fact,i found that all hashs of records are in the 'next' field……If i have 100k records or more, maybe the db can wrok well?so huge data transfering via network would be ok?

**Comment by mccoysc** [comment]
@haadcode

**Comment by haydenyoung** [comment]
Large `next` refs should be addressed in the latest version of OrbitDB. Closing for now but please re-open if problems persist.
