### ISSUE TITLE
Make orbit-db manifest/address verifiable

### ISSUE THREAD

**Issue by thiagodelgado111** [orbitdb/orbitdb#488]
When we get an `orbit-db` address, we need to make sure that that is really the manifest created by the entity we're "assuming" that created it. So one possible solution for it is to add a "signature" as part of the database address so it'd look like this: `/orbitdb/<manifest hash>/<db-name>/<manifest signature>`

That way we can simply load the manifest hash and verify the data on it against the manifest signature part of the address. For that, manifest creation would have to be changed and `orbit-db` addresses too.

As an example, this is what I think the db manifest object could contain:
```
- name: 'my-db'
- type: 'kvstore'
- controller: 'ethereum-wallet/0x6320'  | 'ipfs/QmP0abcd' | 'ethereum-contract/0x1234' | 'orbitdb/<manifest>/<name>/<signature>'
```

(In fact, we could add a lot of metadata there)

**Comment by haydenyoung** [comment]
Is this now implemented? Closing as out-dated but feel free to re-open if applicable still.
