### ISSUE TITLE
TypeError: orbitdb.determineAddress is not a function

### ISSUE THREAD

**Issue by Xinjie-canya** [orbitdb/orbitdb#522]
When I try to use the `Public Instance Methods` -- `determineAddress`, i got this error

And my code is
```js
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {
  // Create OrbitDB instance
  const orbitdb = new OrbitDB(ipfs)
  
  const dbAddress = await orbitdb.determineAddress('users').catch(err => console.log(err))
  console.log('addr', dbAddress())
})
```

I tried to find `determineAddress` method from the source code, but I didn't find that, do you still support that method? Can anyone help me with that?

**Comment by haydenyoung** [comment]
`determineAddress` has been deprecated and is no longer a part of the OrbitDB API. Closing.
