### ISSUE TITLE
The following code in the readme is not working

### ISSUE THREAD

**Issue by veerareddyvishal144** [orbitdb/orbitdb#534]
const ipfs = new IPFS()
ipfs.on('ready', async () => {
  const orbitdb = new OrbitDB(ipfs)
  const db = await orbitdb.keyvalue('first-database')
})

**Comment by aphelionz** [comment]
If you're getting this error:

> `Error: version mismatch: expected v6, found v7`

Here's what's happening: By default your calling new IPFS() with no options will try to connect to your user's IPFS repo in `~/.ipfs` or `~/.jsipfs` depending.

We are looking at a way to reconcile this currently, but for now by simply passing a `repo` option to IPFS, which is a file path, you should be able to work around this. I will create a PR soon to remedy the README.

For example:

> `const ipfs = new IPFS({ repo: "path/to/your/new/repo" })`

**Comment by RichardLitt** [comment]
@vishalveerareddy What error were you getting?

**Comment by haydenyoung** [comment]
Closing as this probably no longer applies to the latest version.
