### ISSUE TITLE
crashes if `heads` is undefined

### ISSUE THREAD

**Issue by jdebeer** [orbitdb/orbitdb#542]
It turns out that `heads` is sometimes `undefined` at this point in the code. Rather than crashing, there should be a protocol to re-try or resolve at this point.

https://github.com/orbitdb/orbit-db/blob/57910eb80b3813046af023a372db6df7e5af2e03/src/OrbitDB.js#L163

**Comment by haydenyoung** [comment]
Is this still an issue with the latest version? Closing for now but please re-open if problems persist.
