### ISSUE TITLE
Unsanitized Input on browser test app

### ISSUE THREAD

**Issue by rahulr311295** [orbitdb/orbitdb#556]
Hi The input for the demo browser app is not sanitized which allows to execute javascript

![image](https://user-images.githubusercontent.com/21986177/52055522-a2940b00-2585-11e9-8330-951106159bd2.png)
![image](https://user-images.githubusercontent.com/21986177/52055537-af186380-2585-11e9-94ad-d887af0ad3e5.png)

![image](https://user-images.githubusercontent.com/21986177/52055571-c35c6080-2585-11e9-9794-99e3acdafe66.png)

**Comment by aphelionz** [comment]
Thank you @rahulr311295

**Comment by haydenyoung** [comment]
Closing as the current demo is outdated. New demos to follow shortly.
