### ISSUE TITLE
Head hash didn't match the contents errors

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbitdb#583]
Several users are reporting this warning

```plain
console.warn node_modules/orbit-db-store/src/Store.js:258
    "WARNING! Head hash didn't match the contents
```

While this seems alarming, it's much more likely a bug in OrbitDB than anything else. We will investigate.

**Comment by decypher93** [comment]
Hello! Have you found the reason of this warning?

**Comment by phillmac** [comment]
Try the latest version, i.e. `0.21.3`. This seems to be fixed.

**Comment by RichardLitt** [comment]
@aphelionz 	Should we close this?

**Comment by aphelionz** [comment]
Affirmative

**Comment by chmanie** [comment]
We are on version 0.21.3 and are still seeing this (a lot). @thiagodelgado111 was working on a fix, maybe he knows more.

**Comment by decypher93** [comment]
not sure though that it's the case but do you have only one db per instance? 
I think i had this warning because i created few bases per one instance.

**Comment by oed** [comment]
I've narrowed it down to this:
It happens with entries I receive from another node on the network.
The reason it happens is because of the keys being in the wrong order. Here is the output from the two hashes that don't match:
```js
Object.keys(a)
(8) ["hash", "id", "payload", "next", "v", "clock", "sig", "key"]
Object.keys(b)
(8) ["hash", "id", "payload", "next", "v", "clock", "key", "sig"]
```

For some reason it seems like the `sig` and `key` property in the object received from another node are swapped. The objects are the same otherwise.

**Comment by chmanie** [comment]
The order of `Object.keys` is not deterministic. If there's a part of the code that relies on that, we should change that. There are libraries like https://github.com/substack/json-stable-stringify that could be used, if necessary.

**Comment by oed** [comment]
I found the issue here: https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L268
By simply logging the two hashes and doing `ipfs.dag.get` on both of them and comparing.
Still not sure where this issue arise. I also don't know which of the entries are incorrect. The already saved one or the one received over network.
Would be interesting to see if you have the exact same issue @chmanie

**Comment by ptoner** [comment]
I've been seeing this a lot lately too. Always when things are being replicated remotely. At this point it seems like it almost always happens. It also seems like it stops the replicated event from firing for some reason.

**Comment by aphelionz** [comment]
@ptoner is this happening on a `v0.21.3` version or higher? also what version of `js-ipfs` are you using?

**Comment by ptoner** [comment]
Good question. Just noticed I've been playing around with the latest stuff. 

orbit 0.22.0-rc4
js-ipfs 0.38.0-pre.1

I had upgraded to the new ipfs because there was mention of some pubsub improvements. But that might be messing with it. I'll drop IPFS back to the latest stable one.

**Comment by aphelionz** [comment]
It's likely they switched the bases around. My guess is that if you do what @oed did you'd see `zdpu...` hashes trying to match with `bafy...` hashes

**Comment by ptoner** [comment]
Seems to both be z ones. 

![orbit-debug](https://user-images.githubusercontent.com/664273/64991135-e3336100-d896-11e9-86d4-fcfb6cd75c21.png)

**Comment by ptoner** [comment]
I've had other issues related to serialization that were unrelated. This might also be. I'll check the underlying objects and see what the difference is.

**Comment by ptoner** [comment]
I downgraded to js-ipfs 0.37.1 and it stopped happening.

**Comment by aphelionz** [comment]
Ok, cool. Closing since we're already planning on supporting future versions of `js-ipfs`

**Comment by oed** [comment]
Ehm, why was this closed? We are still experiencing this issue with `js-ipfs@0.36.4`. Don't think this is related to the ipfs version actually.

**Comment by aphelionz** [comment]
This was happening before because JSON.stringify wasn't deterministic, so I thought this had been fixed. There's likely another culprit not being serialized correctly, or something similar. Retrograding seems to have helped @ptoner which is why I closed it.

Reopened :)

**Comment by koo5** [comment]
getting this with ipfs-js "0.55.3", orbit-db "0.26.1"

**Comment by chrispanag** [comment]
Getting this too with ipfs-http-client "50.1.2" and orbit-db "0.26.1" 

Any workaround? If it helps, we even get a similar (fatal) error when closing and reopening the database. So, most probably, the reordering also happens in the cache.

Any chance a fix will be released soon?

**Comment by chrispanag** [comment]
So got to the bottom of it: 

The problem occurs when there is a `null` value inside the payload. Makes sense.

**Comment by aphelionz** [comment]
Can this be closed?

**Comment by threshhold862543** [comment]
Still occurring in `0.28.6`.

**Comment by threshold862543** [comment]
Actually it seems to only happen with certain types of objects, and null actually works fine it seems.

**Comment by haydenyoung** [comment]
Please test with OrbitDB v1. If the problem persists, please open a new issue.
