### ISSUE TITLE
Key not found in database

### ISSUE THREAD

**Issue by foll27** [orbitdb/orbitdb#587]
I've got a couples of errors wichi i can't fix:
1. The "const ipfs = new IPFS (ipfsOptions) thorw me MaxListenersExceededWarning: Possible EventEmitter memory leak detecte.
2. After runing the code below, I try from the terminal to get info about the db with the "orbitdb info address" command but i recive: Error: Key not found in database [...]

Any tip or solution?
Thanks!

const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}
const ipfs = new IPFS(ipfsOptions)

ipfs.on('error', (e) => console.error(e))
ipfs.on('ready', async () => {
  const orbitdb = new OrbitDB(ipfs)
  const db = await orbitdb.feed('database')
  await db.load()
 
  console.log(db1.address.toString())
 const hash= await db.add('name')
 const value = db.get(hash)
console.log(value)

**Comment by aphelionz** [comment]
Thanks for opening the issue!

We just released the 0.20.0-rc1 (as yet formally unannounced).

Please try `npm install orbit-db@rc1 --save

**Comment by shamb0t** [comment]
Your code looks correct @foll27! Are you able to successfully run it with the latest version of OrbitDB? You no longer need to add the `EXPERIMENTAL` flag if you are using ipfs `v0.38.0` or later

**Comment by haydenyoung** [comment]
This could be an underlying IPFS issue. Try running with latest version of OrbitDB. If the problem persists, please feel free to reopen.
