### ISSUE TITLE
Orbitdb Peers not syncing and Events not calling in Orbitdb version  0.20.0-rc1   (React)

### ISSUE THREAD

**Issue by AqeelKazmi** [orbitdb/orbitdb#596]
Actually i am facing problem that every peer/windowsTab i opened creates his own orbitdb.
```
var id= info.id;   //ipfs created peer id
var peers= db.get('peers');
   
 if(!peers) {
    peers = [id]
    await db.put('peers', peers);
    console.log("list of IF peers:"+db.get('peers'));
} else {
      peers.push(id);
      await db.put('peers', peers);
      console.log("list of ELSE peers:"+db.get('peers'));
  }

```
On opening new peer/windowsTab , it always run if condition and every new peer/windowsTab has its own data only on reading database.

2nd issue is that not even a single event is calling. i am using following events

``` await db.events.on('load', (dbname) => console.log("db loaded....") ); ```
``` 
await db.events.on('replicated', async() => {
  await console.log(`Databse replicated.................................`)
 });
 ```
``` 
 await db.events.on('ready', (dbname, heads) => console.log("dbname:"+dbname) ) 
```

**Comment by AqeelKazmi** [comment]
I am sure there is some issue in syncing and event side of this new version of orbit db.

**Comment by AqeelKazmi** [comment]
@haadcode @aphelionz  guys look here please. I need it urgent .
Your replies will be highly appreciated

**Comment by aphelionz** [comment]
Hi @AqeelKazmi, thanks for creating this issue. I'm sorry you're having trouble with this. The team is currently traveling right now but we are aware of your issue and will be able to take a look ASAP.

**Comment by AqeelKazmi** [comment]
@aphelionz  please update me when you guys get it done as i have some working dependencies.

**Comment by haydenyoung** [comment]
Please try with latest code base. If problem persists, please feel free to open a new issue.
