### ISSUE TITLE
Error: Not a valid OrbitDB address

### ISSUE THREAD

**Issue by smackthat** [orbitdb/orbitdb#634]
Greetings.

Creating a new database doesn't work. Running on Windows.

Here's some of my code:

`const ipfs = ipfsClient('/ip4/192.168.99.101/tcp/9095');`
`var orbitdb = await createInstance(ipfs);`
`var db = await orbitdb.create('test', 'docstore');`

And here's the error:

`Error: Not a valid OrbitDB address: \orbitdb\zdpuAtaYCzrVNYnqFz2rZj8FSQZkzAR5659xX6EEB6PWrmfFz\test
at Function.parse (C:\Documents\foo\node_modules\orbit-db\src\orbit-db-address.js:44:13)
at OrbitDB._determineAddress (C:\Documents\foo\node_modules\orbitdb\src\OrbitDB.js:257:27) at <anonymous>`

Something do with the backslashes?

EDIT: OrbitDB version 0.20.0

**Comment by movefasta** [comment]
Switching to previous js-ipfs version can help
In ipfs@0.36.0 cid encoding changed - https://github.com/ipfs/js-ipfs/releases/tag/v0.36.0

**Comment by smackthat** [comment]
Hi,

Switched to ipfs@0.35.0, but the error persists.

Debugged the orbit-db-address-js, and the error there is caused in the isValid-method. The parts of the address are not split correctly because of the backslashed in the address. 

The catch block of the isValid-method shows `Error: Non-base58 character` due to trying to encode the whole address string (eg. "\orbitdb\zdpuAvaTkVHHAvZiasT1HoprBawd9wM7AUGXueirbnmPUThAC\test").

**Comment by aphelionz** [comment]
Ahh, ok. we are working on windows support as we speak! Sorry for the delay. Please see this branch in the meantime: https://github.com/orbitdb/orbit-db/pull/607

**Comment by mohe2015** [comment]
> Switching to previous js-ipfs version can help
> In ipfs@0.36.0 cid encoding changed - [ipfs/js-ipfs@`v0.36.0` (release)](https://github.com/ipfs/js-ipfs/releases/tag/v0.36.0)

Is there any plan to fix this?

**Comment by aphelionz** [comment]
Yes we're working on upgradung the `orbit-db-io` module to support the new base

**Comment by iohzrd** [comment]
can confirm this issue persists on:
windows + orbit-core v0.2.0-rc1 in conjunction with ipfs-http-client v45.0.0
any ETA on when this will be resolved? or any suggestions as to how I can help resolve?

**Comment by iohzrd** [comment]
ah, NVM, I see it's been fixed upstream.

**Comment by haydenyoung** [comment]
Closing as appears to be fixed. This issue may also be resolved by the latest version of OrbitDB.
