### ISSUE TITLE
Replication Paging

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbitdb#645]
As it stands right now, after a heads exchange, the OrbitDB replicator will load _all_ availale entries. It would be good to be able to pass in some sort of parameter (either an integer value, an end hash, or a lamport clock time) to limit the amount of replication. This should allow the developer greater control over how much replication occurs.

The default should remain as loading the entire db

**Comment by oed** [comment]
This would be awesome :D

**Comment by haydenyoung** [comment]
Closing. I'm not sure this applies any more as lazy loading using iterators is now implemented in version 1.
