### ISSUE TITLE
... as unexpected token

### ISSUE THREAD

**Issue by pragmaticadam** [orbitdb/orbitdb#650]
Hi
I'm trying to use OrbitDB in my Vuejs application 

I configured babel 7 but I still cannot manage OrbitDB to compile properly. 
whene in one of my modules i do 

import * as OrbitDB from 'orbit-db';

I'm getting

```
in ./node_modules/orbit-db-access-controllers/src/orbitdb-access-controller.js

Module parse failed: Unexpected token (51:8)
You may need an appropriate loader to handle this file type.
|       // and make sure all values are Sets
|       Object.entries({
|         ...capabilities,
|         // Add the root access controller's 'write' access list
|         // as admins on this controller
```

**Comment by pragmaticadam** [comment]
Is there any already compiled version of orbitdb ? like ipfs has for example:
https://unpkg.com/ipfs/dist/index.js

**Comment by shamb0t** [comment]
Hi @pragmaticadam are you able to use the build provided in `dist/orbitdb.min.js`? It looks like babel 7 doesn't support the spread operator and some more configuration is needed. I suggest using the distribution provided or trying a plugin like `@babel/plugin-proposal-object-rest-spread`.

**Comment by adamskrodzki** [comment]
Hi, when I tried to use unpkg.com/orbit-db/dist/orbitdb.min.js things works as expected. 

Still would be great if I was able to use sourcecode not minified version

**Comment by RichardLitt** [comment]
@adamskrodzki 	Did you try using the Babel plugin @shamb0t 	suggested? That might work without having to use the sourcecode.

**Comment by RichardLitt** [comment]
Thanks for the feedback. :) Sorry that didn't work out.
