### ISSUE TITLE
KevValue Iterate

### ISSUE THREAD

**Issue by anywhichway** [orbitdb/orbitdb#659]
I note that the kvstore API does not have a `keys` or `iterate` function. are these in the works? possible? not possible given architecture?

**Comment by aphelionz** [comment]
Possible! In fact you should be able to simply do something like:

```JavaScript
await db.load()
Object.keys(db._index._index)
```

**Comment by aphelionz** [comment]
Not a bad idea to abstract that out into a function. Perhaps worthy of a PR in https://github.com/orbitdb/orbit-db-kvstore?

**Comment by anywhichway** [comment]
> Possible! In fact you should be able to simply do something like:
> 
> ```js
> await db.load()
> Object.keys(db._index._index)
> ```

So the keys are in RAM, or is _index a getter? If keys are in RAM we are going to run into some issues ... got some data sets with massize numbers of keys.

**Comment by aphelionz** [comment]
`db.load()` will load the data from IPFS into RAM, yes.  

You may be able to mitigate tis by passing an integer into `load` as its argument to limit the amount loaded. See here: https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L208

**Comment by phillmac** [comment]
Don't forget the public `db.index` is thing, so you don't have to use private _index

**Comment by phillmac** [comment]
> > Possible! In fact you should be able to simply do something like:
> > ```js
> > await db.load()
> > Object.keys(db._index._index)
> > ```
> 
> So the keys are in RAM, or is _index a getter? If keys are in RAM we are going to run into some issues ... got some data sets with massize numbers of keys.

The index for the kvstore is entirely in RAM. See here: [KeyValueIndex.js](https://github.com/orbitdb/orbit-db-kvstore/blob/master/src/KeyValueIndex.js )

**Comment by MeirionHughes** [comment]
Any plans to add the iterator to the KV store? 
Is this DB suitable to for KV stores with millions of keys and sum of Values > than RAM size? 

I'm coming from using levelDB, where I use the fast range queries a lot (but immutable, append writes)... but I have a requirement for db-db replication. Just wondering is Orbit is suitable or not (it does everything else I need, except the KV iterator).

**Comment by haydenyoung** [comment]
See the new `iterator` and `all` functions in the databases and whether they address your use cases.
