### ISSUE TITLE
saveSnapshot is not a valid json

### ISSUE THREAD

**Issue by adamskrodzki** [orbitdb/orbitdb#668]
Hi,
I've executed saveSnapshot
below example content

https://gateway.pinata.cloud/ipfs/QmUU4MFyn7UG64rLynvqZiYLA3v4ueX8jfgpYNt4e2csKu/

from databasee running here

https://gateway.pinata.cloud/ipfs/QmUVgQPCGd4XiGHbTAco3ZYCGK6fxjxuZRDwBXDj2gfE8c/#/

Is there any reasson why it is not a valid json? 
How to parse it?

I'm using Ethereum blockchain for peer discovery, to speed up synchronisation.
 currently I'm sending only peer address and that sometimes ends with "node" unreachable kind of error. I wanted to send IPFS hash of snapshot, so any node can download some recently new database even if node having it is no longer reachable

**Comment by adamskrodzki** [comment]
looks kind like 'it is not a bug, it is a feature' kind of thing ;) 


    let size = new Uint16Array([header.length])


     let size = new Uint16Array([str.length])


that is what causes this strange characters,

it would be better if that was simply an array where first element is header 

and all next are delimited by ,


I understand that You do not want to build one json and stringify it at once to decrease memory consumption of serialization, but that  approach do not have bigger memory requirements than Yours

**Comment by haydenyoung** [comment]
Closing as OrbitDB version 1 does not include snapshotting.
