### ISSUE TITLE
Pass all entries to `AccessController.canAppend`

### ISSUE THREAD

**Issue by JamesLefrere** [orbitdb/orbitdb#680]
Currently, the interface for this method looks [like this](https://github.com/orbitdb/orbit-db-access-controllers/blob/2954a344aefcef21953ff35c69ae3953b989e037/src/access-controller-interface.js#L40
)

```typescript
async canAppend(entry: Entry, identityProvider: IdentityProvider): boolean {}
```

I have a use case where I need to check the entry to be appended against the values of previous entries, so this kind of interface would be helpful:

```typescript
async canAppend(entry: Entry, identityProvider: IdentityProvider, entries: Entry[]): boolean {}
```

Would this be possible? Or should I look into checking this outside of the access controller?

Cheers

**Comment by phillmac** [comment]
Let me just say first off, I'm by no means an expert here, just a junior really.
It seems to me that what your trying to do is data validation, which is in most cases a separate concern to access control. 
I'm going to guess wildly here that your doing something block-chain related?

**Comment by JamesLefrere** [comment]
Thanks for the input. This isn't data validation, but rather role-based access control.

Here's a scenario:

1. An entry is appended to the log by Alice, that represents setting the 'group' (of whatever the log is for) to X.
2. Bob attempts to set the 'group' to Y. He's a member of group Y, but not group X.
3. The custom access controller ought to examine all entries on the log; in this case, so that that the identity is valid for both the most-recent and to-be-appended entries.

**Comment by shamb0t** [comment]
Thanks for your question @JamesLefrere! It's not currently possible to pass in an entries list but perhaps a custom orbit-db based access controller could help? The [orbit-db-access-controller](https://github.com/orbitdb/orbit-db-access-controllers/blob/master/src/orbitdb-access-controller.js) currently only checks the `write` capability but you could create a similar one which sets the group with a call like `db.access.grant('group','X')` and change the `canAppend` function to check that `entry.identity` is part of a group that matches?

```
  async canAppend (entry, identityProvider) {
    // Get the groups
    const access = new Set([...this.get('group')])

    const appendersGroup = getGroup(entry.identity) // 'X'
    if (access.has(appendersGroup) || access.has('*')) {
      const verifiedIdentity = await identityProvider.verifyIdentity(entry.identity)
      // Allow access if identity verifies
      return verifiedIdentity
    }
    return false
  }
```

  Not sure if this is helpful. Does sth like this sound possible for your use-case?

**Comment by haydenyoung** [comment]
Closing. The recommended solution would now be to roll your own AC. Any issues, feel free to re-open or create a new issue.
