### ISSUE TITLE
Multiple orbit-db instances in one nodejs application?

### ISSUE THREAD

**Issue by Bambofy** [orbitdb/orbitdb#705]
Hi, i'm just wondering whether one nodejs application can run multiple instances of ipfs/orbit-db at a time?

**Comment by tabcat** [comment]
ive ran multiple orbitdb instances from one ipfs instance before and now its recommended to hand a single ipfs instance to a single orbitdb instance so id guess running multiple ipfs instances is also possible and fine.

**Comment by phillmac** [comment]
If I recall correctly there was some issues with pub-sub messages not being broadcast properly, so if you run into any issues with replication between orbit db peers attached to the same ipfs node, you should know where to look :grin:

**Comment by haydenyoung** [comment]
Closing. The latest version of OrbitDB allows for multiple instances to be run from a single node app. @tabcat and @phillmac have also provided additional help. If any problems persist, feel free to re-open this issue.
