### ISSUE TITLE
Live demo no longer working: Websocket error

### ISSUE THREAD

**Issue by MirceaKitsune** [orbitdb/orbitdb#708]
https://ipfs.io/ipfs/QmRosp97r8GGUEdj5Wvivrn5nBkuyajhRXFUcWCp5Zubbo

The official live example no longer appears to be functional: At the bottom of the page I see a "websocket error" after the script attempts to start IFPS for roughly 20 seconds.

![Screenshot_20191013_211609](https://user-images.githubusercontent.com/825418/66719929-c55a0d00-edfe-11e9-93c3-2ee594c7ff34.png)

This happens in both Chromium 77.0.3865.90 and Firefox 69.0.2.

**Comment by johtso** [comment]
Any update on this? Would be nice to have a working example to work from..

**Comment by tabcat** [comment]
@johtso yes, this demo was updated recently. It is linked by the name Demo 1 on the README and can be ran locally with scripts in `package.json`.

here is the new link the README refers to now.
https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/

TodoMVC demo link has not been updated yet but a PR was made that fixes issues with it.
https://github.com/orbitdb/example-orbitdb-todomvc/pull/11

**Comment by aphelionz** [comment]
Should be fixed, thanks @tabcat
