### ISSUE TITLE
Update Feed Store DB field

### ISSUE THREAD

**Issue by sdelvalle57** [orbitdb/orbitdb#711]
Hey Guys.

IM recently working with a feed DB, everything works good when I add new fields, but how can I update an already created field without having to change its hash?
Cannot get to find the right documentation for this.

Steps Im trying to achieve are:
```
    //Load DB, this works as expected
    const orbitdb = await OrbitDB.createInstance(ipfs);
    const db = await orbitdb.feed(dbName);
    await db.load();

    //Add a new object to OrbitDB, works ok
    const dbObject = {name: "Santiago", lastName: "Del Valle"};
    const hash = await db.add(dbObject);

    //Wait for some interactions then update the object, not sure how, I will assume any method for the moment
    await db.add(hash, {age: 30};
    //so at the end object in db should be {name: "Santiago", lastName: "Del Valle", age:30} under the initial hash

Thanks

**Comment by aphelionz** [comment]
@sdelvalle57 I think what you're looking for is either `orbit-db-kvstore` or `orbit-db-docstore` - The feed store is only a thin layer on top of the `orbit-db-eventstore` which is in turn a thin layer on top of a raw oplog. It more or less stores arrays of values but the afotementioned kvstore and docstore are a bit more robust in terms of a data view

**Comment by haydenyoung** [comment]
Closing as @aphelionz has provided feedback. Also, a `feed` db is no longer supported out-of-the-box. Please re-open if you are still experiencing problems.
