### ISSUE TITLE
Open Remote Database in OrbitDB Example not working on master

### ISSUE THREAD

**Issue by bnchrch** [orbitdb/orbitdb#727]
_Hey all Ben from Fission here I either found a bug or need a hand. More below!_

# Summary
Using [Live Demo 1](https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/) in the `README` on `master` works fine in everycase. However if I checkout master and run the examples locally I cannot open any remote database.

I am unsure if this is a bug or I am using OrbitDB incorrectly. Would love a hand figuring out which of these it is 😅 

# Steps to reproduce
## In Browser
1. Navigate to [Live Demo 1](https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/)
1. Create a Public database and copy the OrbiDB address
1. clone `orbit-db`
1. run the browser example using `npm i && npm run build:examples && npm run examples:browser-macos`
1. a page should open. take the OrbitDB address from step 2 and paste it into `Open Remote Address

**Expected Result:** It should connect to the remote db and start showing the feed
**Actual Result:** It fails with the following error:

### Digging in
![image](https://user-images.githubusercontent.com/1325608/68905049-1494a580-06fd-11ea-853a-8d64d6a34035.png)
Tracing this back left me that the `ipfs.dag.get` failed here in `orbit-db-io`
https://github.com/orbitdb/orbit-db-io/blob/master/index.js#L46
NOTE: The CID was successfully passed in

## In Node
1. Navigate to [Live Demo 1](https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/)
1. Create a Public database and copy the OrbiDB address
1. clone `orbit-db`
1. edit the `eventlog.js` file to use the OrbitDB address from step 2 (hardcoded) [(exact line here)](https://github.com/orbitdb/orbit-db/blob/master/examples/eventlog.js#L27)
1. run the node example using `npm i && npm run build:examples && npm run examples:node`

**Expected Result:** It should connect to the remote db and start showing the feed
**Actual Result:** It fails with the same error from the browser:
![image](https://user-images.githubusercontent.com/1325608/68905313-fe3b1980-06fd-11ea-822b-e1b323fc0e36.png)

# Appendix
### Working across incognito
![Screen Shot 2019-11-14 at 4 08 43 PM](https://user-images.githubusercontent.com/1325608/68905346-2296f600-06fe-11ea-8df6-c54e271409b2.png)

### Working across browsers
![Screen Shot 2019-11-14 at 4 13 30 PM](https://user-images.githubusercontent.com/1325608/68905364-304c7b80-06fe-11ea-8dd2-eeb86e72e7af.png)

### Failing locally
![Screen Shot 2019-11-14 at 4 09 30 PM](https://user-images.githubusercontent.com/1325608/68905374-3c383d80-06fe-11ea-8b75-a77b8b21c719.png)

### Failing on node
![Screen Shot 2019-11-14 at 4 28 44 PM](https://user-images.githubusercontent.com/1325608/68905388-45c1a580-06fe-11ea-9fb7-62695d8e678f.png)

**Comment by shamb0t** [comment]
Thanks @bechurch, the live demo is indeed out of date and an updated version needs to be republished to ipfs!

To build the example code and try out for yourself you can run that `npm i && npm run build:examples` and open `examples/browser/browser.html` in one window and open it again in another incognito window to open a remote database. Are you successfully able to run the example that way?

**Comment by bechurch** [comment]
Hey @shamb0t!

Thanks for replying so fast! Everything you said worked as expected and I was able to continue on exploring OrbitDB. Really awesome stuff youve built. I particularly like how extendable and customizable you've left the stores! 🎉 

Hey I also wanted to ask how I could build the examples for deploying to IPFS? It doesn't seem like they work too well by just pushing the examples folder after building.

As an FYI the reason I'm curious is I think I see a way we could help you out! If we have an easy way to get those examples IPFS ready we could add `fission live` to your `CI/CD` pipeline so that when you push to master we:

1. build the assets
2. push to IPFS
3. update the ipfs DNS records for a subdomain like `orbitdb-demo-1.runfission.com`

That way we don't ever have to worry about those going stale again. Anyway If you think that'd be helpful just let me know and I can start pushing it through on my end.

**Comment by aphelionz** [comment]
@shamb0t @haadcode and I talked about this proposal and the answer is... yes, please! This seems like a great, low-effort way to combine forces and show each other's tech off. Go ahead and make a branch for it, and we'll take it from there.

**Comment by bechurch** [comment]
@aphelionz Great. We've got the ball rolling on our end. We should be able to have this for you in the next couple weeks!

**Comment by haydenyoung** [comment]
Closing as no further discussion but feel free to re-open if applicable.
