### ISSUE TITLE
Feed ownership is confusing in the FAQ

### ISSUE THREAD

**Issue by illeatmyhat** [orbitdb/orbitdb#751]
As far as I understand from the FAQ, OrbitDB allows users to subscribe to a persistent pubsub feed that is owned and administrated by an individual, if the correct writer permissions are applied.

I think the two sections below can be merged into a more widely-encompassing article about how administration and the data model works in OrbitDB:
>Does orbit have a shared feed between peers where multiple peers can append to the same feed?

which implies that the whole of OrbitDB is an uncontrolled riot like a publicly editable Google Doc

>Does OrbitDB natively allow for a multi-writer capability permission model?

which implies that there is in fact, an owner (though by default it's nobody)

**Comment by haydenyoung** [comment]
These FAQs are probably out-dated now. Closing but if this is not addressed by the new documentation, please feel free to re-open.
