### ISSUE TITLE
Verify log entries from network, don't verify again if loaded from memory

### ISSUE THREAD

**Issue by zachferland** [orbitdb/orbitdb#753]
To speed up loading logs, entries which are loaded from memory dont have to be verified again, assuming they were verified when written. 

Would rely on some assumptions (that seem true right now). That reader and writer from storage layer are the same (or single reader/writer) and that local/remote heads if in your cache were are heads of logs you loaded/verified once before. Then you can load stores from those heads with our verifying sigs. 

Only entries when first replicated from network would need to be verified 

would need in issue in ipfs log as well

**Comment by vaultec81** [comment]
I think this is a good endeavor for a future PR. However, the nature of orbit-db CRDTs there is no certainty whether a entry is added to the oplog or just recently replicated (It is measurable, just not implemented). My concern is changes that are made to the access controller wouldn't be realized until after the conflicting oplog entries are written to the disk. Orbit-db does not have a formal system to handle conflicts or old oplog entries that appear newly replicated, but this currently isn't a problem as the access controller does not support adding/revoking access.

Verifying based off a head hash would be the first step. Re-indexing from old but recently replicated oplog entry would be required. Again this isn't an issue now. Just my thoughts,

**Comment by haydenyoung** [comment]
Closing as may no longer apply to newer versions of OrbitDB.
