### ISSUE TITLE
data can't read/update by other peer

### ISSUE THREAD

**Issue by bluelovers** [orbitdb/orbitdb#761]
code 1 run in codesandbox

https://codesandbox.io/s/agitated-dew-vqekz

code 2 run in local pc

```ts
import IPFS from 'ipfs'
import OrbitDB from 'orbit-db'

import Identities from 'orbit-db-identity-provider';

// Create IPFS instance

// For js-ipfs >= 0.38
const ipfs = new IPFS()

ipfs.on('error', (e) => console.error(e))
ipfs.on('ready', async () => {

	const options = { id: 'local-id' }
	const identity = await Identities.createIdentity(options)

	console.dir(identity.toJSON())

	const orbitdb = await OrbitDB.createInstance(ipfs)

	const dbAddress = await orbitdb.determineAddress('hello', 'keyvalue', {
		accessController: {
			write: [
				//orbitdb.identity.publicKey,
				//orbitdb.identity.id,
				'*',
			]}
	})

	console.log(`dbAddress`, dbAddress)

	// Create / Open a database
	const db = await orbitdb.kvstore(dbAddress, {
		accessController: {
			write: [
				//orbitdb.identity.id,
				'*',
			],
		},
	});
	await db.load()

	console.log(db.identity.id)
	console.log(db.identity.publicKey)

	console.dir(db.address.toString())

	// Add an entry
	let hash: string

	hash = await db.get('world')
	console.log('hash', hash)

//	hash = await db.put('world', { updated: Date.now() })
//	console.log('hash', hash)
//
//	hash = await db.get('world')
//	console.log('hash', hash)

	await orbitdb.disconnect()

	await ipfs.stop();
})

```

`dbAddress` is same = `/orbitdb/zdpuAwasWRQmp6B937QDsm8V9oM3a2N8VAGkGVNctBsGTxgan/hello`

but i can't see `{ updated: 7777777 }` when run code 2 at local pc

**Comment by aphelionz** [comment]
Hi @bluelovers thanks for opening this issue and thanks for your patience in waiting for this reply.

The two peers will not be able to replicate data if they are not connected, and depending on your version of `js-ipfs`, they might be swarming via DHT sufficiently enough to automatically connect. One thing you can try is to use a websocket server such as https://github.com/libp2p/js-libp2p-websocket-star-rendezvous. Note there is a public server for development use here: https://ws-star.discovery.libp2p.io/

Once both peers are connected to that then they should be able to share data.

**Comment by bluelovers** [comment]
hmm, thx, but how can i use this server in orbit-db?

**Comment by aphelionz** [comment]
When you instantiate IPFS, you can include that server as a swarm node. There's an example in our `orbit-db-test-utils` repo here: https://github.com/orbitdb/orbit-db-test-utils/blob/master/config/browser.js#L69

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/74769776-fa530080-52c5-11ea-8ba5-69be269f4a35.png)

1 & 2 should is same number, but it not same

**Comment by aphelionz** [comment]
It looks close! Can you now confirm that the two peers are connected and swarming together and that they can receive pubsub messages from each other?

**Comment by bluelovers** [comment]
https://codesandbox.io/s/agitated-dew-vqekz

![image](https://user-images.githubusercontent.com/167966/74774606-08594f00-52cf-11ea-80ed-c3e011d96516.png)

![image](https://user-images.githubusercontent.com/167966/74774704-2cb52b80-52cf-11ea-9696-832052ae14cb.png)


![image](https://user-images.githubusercontent.com/167966/74774676-2030d300-52cf-11ea-8240-db75030f12ad.png)

still can't get same number

**Comment by bluelovers** [comment]
i try use 

```
{
				port: 5001,
				host: 'ipfs.infura.io',
				protocol: 'https',
			}
```

it still can't read/update same db

run this code multe time

```ts
import OrbitDB from 'orbit-db'

import useIPFS from 'use-ipfs';
import ipfsServerList from 'ipfs-server-list';



useIPFS({}, {
	fallbackServer: ipfsServerList['infura.io'].API,
	useFallbackFirst: true,
})
	.then(async (ipfs) => {

		const orbitdb = await OrbitDB.createInstance(ipfs.ipfs, {
			id: '777',
			//offline: true,
			directory: './orbitdb' + String(Math.random()),
		});

		const dbAddress = await orbitdb.determineAddress('hello', 'keyvalue', {
			accessController: {
				write: [
					'*',
				]}
		})
		;

		const db = await orbitdb.kvstore(dbAddress, {
			accessController: {
				write: [
					'*',
				],
			},
		});

		// @ts-ignore
		process.once('SIGINT', async (...argv) => {
			try
			{
				return orbitdb.disconnect()
			}
			catch (e)
			{

			}

		});

		let hash: unknown;

		hash = await db.get('world')
		console.log('hash', hash)

		hash = await db.put('world', { updated: new Date().getSeconds() })
		console.log('hash', hash)

		hash = await db.get('world')
		console.log('hash', hash)


	})
;

```

**Comment by obernardovieira** [comment]
Hi,

I'm having the same problem. I've applied some changes after looking at your code, but I've got the same problem.

In my case, I'm using two different browser, same machine. Determine the address and start a keyvalue from it. But nothing shows up in the second.

For reference, I'm loading the database here https://github.com/dlx-lisbon/dlx-ui/blob/master/src/App.tsx#L71 and uploading data here https://github.com/dlx-lisbon/dlx-ui/blob/master/src/NewContent.tsx#L56
But in fact, the *replicated* event (here https://github.com/dlx-lisbon/dlx-ui/blob/master/src/NewContent.tsx#L52 )never gets called.

What am I doing wrong?

**Comment by haydenyoung** [comment]
Is this still an issue with the latest OrbitDB version? Closing for now but if problems persist, please re-open this issue or start a new one.
