### ISSUE TITLE
Syncing to and from a single head hash

### ISSUE THREAD

**Issue by vaultec81** [orbitdb/orbitdb#774]
Context: Currently orbit-db has no mechanism to represent the current state in a single hash. The closest thing to this is comparing a list of head hashes, and trans-versing the dag of each head in the head list. This can be seen in [orbit-db-store sync()](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L264-L317), which is the current logic used for syncing the database across nodes. There is no way for application developers wanting to export their current state hash and publish that same state hash to other nodes. Then verify that all nodes across the database are synced to exactly the same point. There is no easily verifiable certainty that every node hosting a database is viewing the same state. 

A possible solution would be adding two new methods. `toHeadHash()` would export a single hash representing the current head hashes in a dag cbor object. `SyncFromHeadHash()` would iterate through the represented dag cbor object. Syncing each head in the process and guaranteeing the database is properly synced. The method will queue all read write operations until the syncing has been completed. 

This is an on going discussion. Feedback is welcomed.

**Comment by aphelionz** [comment]
Note that this can _almost_ be done in [`ipfs-log#fromEntryHash`](https://github.com/orbitdb/ipfs-log/blob/ba2ec2d1c1b07728fab851efe431aa62c95fe8b1/src/log.js#L571), but for only one hash

**Comment by vaultec81** [comment]
Check out this [commit ](https://github.com/dappkit/ipfsdb/commit/fca64d7c6f819331952c615afe69b74cca550ab8) which adds support for syncing to from a single head hash. I suppose something similar can be added to orbit-db-store.

**Comment by aphelionz** [comment]
Looks pretty cool!

**Comment by haydenyoung** [comment]
Closing as commit is probably out-of-date. Feel free to submit a new PR if still applicable to version 1.
