### ISSUE TITLE
ATTN: Codesandbox starter template for issues

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbitdb#775]
I've created an [OrbitDb starter template](https://codesandbox.io/s/orbitdb-starter-template-4c8qu) here on codesandbox.io. I used that instead of jsfiddle because jsfiddle breaks in Brave with shields up :( Feel free to fork so we can actively hack on any issue you may have. 

Finally, feel free to comment here with starter templates from other code playground sites and I'll include them. It'd be nice to have a roster of these in the end.

**Comment by revolunet** [comment]
thanks, that's great to hack with the field manual 🙏 

would be great to have a browser version too but for some reason, codesandbox doesnt want to load the dependencies https://codesandbox.io/s/interesting-breeze-6grzn?file=/src/App.js

**Comment by phillmac** [comment]
@revolunet 
`"ENOSPC: no space left on device, write"`
The storage space limitations aren't big enough to handle ipfs and its deps.
This is simply a limitation of codesandbox for browser type templates. The only way around this is to use a nodejs base template and manually run a webserver process in node or something to host the app & assets

**Comment by revolunet** [comment]
has someone tried orbitdb with [js-ipfs-lite](https://github.com/textileio/js-ipfs-lite) ?

**Comment by phillmac** [comment]
Does it support pubsub?

**Comment by phillmac** [comment]
Same error.
```
error Could not write file "/tmp/293041717/yarn-error.log": "ENOSPC: no space left on device, write"
error An unexpected error occurred: "ENOSPC: no space left on device, copyfile '/tmp/293041717/v6/npm-cids-0.7.5-60a08138a99bfb69b6be4ceb63bfef7a396b28b2-integrity/node_modules/cids/docs/assets/fonts/WOFF2/TTF/SourceCodePro-Regular.ttf.woff2' -> '/tmp/293041717/node_modules/cids/docs/assets/fonts/WOFF2/TTF/SourceCodePro-Regular.ttf.woff2'".
```

**Comment by phillmac** [comment]
Here's a copy of your template with the nodejs base that seems to work ok:
https://codesandbox.io/s/thirsty-chatelet-y8cem

**Comment by revolunet** [comment]
Thanks @phillmac , ive just understood your comment 

> This is simply a limitation of codesandbox for browser type templates. The only way around this is to use a nodejs base template and manually run a webserver process in node or something to host the app & assets

So this is still a 100% full browser version, we only use node to bypass some codesandbox issue

**Comment by haydenyoung** [comment]
Closing.
