### ISSUE TITLE
Manifest & access controller becomes unpinned by ipfs repo GC

### ISSUE THREAD

**Issue by phillmac** [orbitdb/orbitdb#792]
We need to automatically  pin both the manifest and the access controller during db open to prevent go-ipfs from deleting them while performing repo garbage collection.

**Comment by tabcat** [comment]
I'm guessing you would also unpin the data when the store is dropped

**Comment by mistakia** [comment]
I don't see this documented anywhere, but I think if you pass `{ pin: true }` to `orbitdb.create` that may pin the manifest. I'm not sure if that will recursively pin the access controller. My guess is no.

From what I can tell there is no way to pin the ac or manifest for an already created db.

**Comment by aphelionz** [comment]
Started work on this at the ACL level here: https://github.com/orbitdb/orbit-db-access-controllers/pull/45

**Comment by aphelionz** [comment]
Unfortunately `pin: true` will not work :(

**Comment by haydenyoung** [comment]
Closing as probably out-dated with version 1 release. If the problem persists, feel free to reopen.
