### ISSUE TITLE
Electron: net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by tymmesyde** [orbitdb/orbitdb#802]
My goal is to open and listen to multiples databases from peers.
But it seems that when I open more than one remote database, the module `ipfs-peer-monitor` used by the `orbit-db-pubsub` package sends too many requests to get the peers of the topic and not waiting for them to finish.
Requests starts to be pending and result in errors after a while:
`[ERROR] pubsub: [TypeError: Failed to fetch]` and `net::ERR_INSUFFICIENT_RESOURCES`.

![Screenshot_205](https://user-images.githubusercontent.com/7889816/84933067-9b679180-b0d5-11ea-8db0-512d18a6012c.png)
![Screenshot_206](https://user-images.githubusercontent.com/7889816/84933078-9e628200-b0d5-11ea-95d1-a7d1d4f3290f.png)

What the peers are doing:
- Spawn an ipfs daemon
- Connect to the api using `ipfs-http-client`
- Instantiate OrbitDB
- Create dbs
- Using pubsub to subscribe to the same topic, exchange their multiaddress and oribitdb identity.
- Swarm connect each others.
- Guess the remote addresses from the identity.
- Open and Load the remote dbs.
- Listen for `replicated` event

This run in a browser (electron).

I don't really understand what is going on ? 
Is there something I missed ?

**Comment by tymmesyde** [comment]
I made a repo so you can reproduce my issue: https://github.com/tymmesyde/electron-orbitdb-issue
I hope it will be clearer

**Comment by haydenyoung** [comment]
Is this still applicable with latest OrbitDB version? Closing but feel free to re-open if applicable.
