### ISSUE TITLE
libp2p-keychain@0.6.1: No longer supported for js-libp2p0.28.0 or later

### ISSUE THREAD

**Issue by WillGone704** [orbitdb/orbitdb#803]
Hey guys,

A few minutes ago I tried to install orbit-db and npm throw this error: 
`npm WARN deprecated libp2p-keychain@0.6.1: No longer supported for js-libp2p0.28.0 or later`

**Comment by haydenyoung** [comment]
Looks like a libp2p issue. Will close this due to outdated version of OrbitDB but if the problem persists with v1, feel free to re-open.
