### ISSUE TITLE
how to config replication Factor？

### ISSUE THREAD

**Issue by bitcard** [orbitdb/orbitdb#808]
does oribit-db has replication Factor？
if has one, how to config? 
If no, if add data on node1, but it go offline, the data can get from other node?
thanks.

**Comment by haydenyoung** [comment]
By replication factor do you mean for every record there are n copies guaranteed elsewhere? No, this is not baked into OribtDB but you could implement if you required it. OrbitDB can be replicated across other nodes and dbs can be pinned to 3rd party pinning services for guaranteed up-time.
