### ISSUE TITLE
it base on ipfs-log, what happen when delete data?

### ISSUE THREAD

**Issue by bitcard** [orbitdb/orbitdb#815]
orbit-db base on ipfs-log,  it's Append-only log, does mean can't delete data? thanks.

**Comment by phillmac** [comment]
Yup. You can 'drop' the database and delete the log entirely, if you need to keep.some of the data you can create a fresh db

**Comment by bitcard** [comment]
> Yup. You can 'drop' the database and delete the log entirely, if you need to keep some of the data you can create a fresh db

thanks for your reply.

1, If can't delete, it meaning the data became bigger and bigger.
2, If the data is very big, create a new one, it may take a long time.
3, so if application use orbit-db, how to scale up application?

**Comment by phillmac** [comment]
Most scaling techniques mean using some soet of sharding

**Comment by bitcard** [comment]
> Most scaling techniques mean using some sort of sharding

how to config sharding, is there a document about it?

**Comment by tabcat** [comment]
> how to config sharding, is there a document about it?

there is not but it might be something fun to build!

**Comment by aphelionz** [comment]
I can see some sharding-alike behavior happening in two places. One easy, one harder:

1. At the time of remote->local replication, there is a verification step that can block an entry being replicated locally into the db. You could add a validation step there, and then simply neither replicate nor calculate the state of the "invalid" entries
2. Theoretically, nodes could publish their preferences on what they want to replicate onto the DHT, and then you could perhaps block pubsub _sending_ of messages to those nodes on the sender side. This could reduce network traffic substantially but I'm not sure of such features exist at the pubsub level as of now

Also,

Q: How do you make sure all of this doesn't mess with the integrity of the local DB state? 
A: Very carefully :wink:
