### ISSUE TITLE
Browser ipfs-http-client to go-ipfs localhost node... getting status 400 bad request

### ISSUE THREAD

**Issue by thienpow** [orbitdb/orbitdb#818]
**browser webapp**
"orbit-db": "^0.24.2",
"ipfs": "^0.47.0", also tested 0.46.0 result is same.
**go-ipfs**
0.6.0

Error:

```
http://127.0.0.1:5001/api/v0/pubsub/sub?arg=%2Forbitdb%2FzdpuB2sR2Q1J1fU2LpKkUp7NC1zfP4jj9RQHVQbeaVSowtPAy%2Fhistory
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

already did the following

```bash
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin  '["http://127.0.0.1:3000", "http://localhost:3000", "http://localhost:5001", "http://127.0.0.1:5001", "https://webui.ipfs.io", "http://webui.ipfs.io.ipns.localhost:8080"]'
    ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["GET", "PUT", "POST"]'
```
and started ipfs with 
```bash
 ipfs daemon --enable-pubsub-experiment
```
my web started from localhost:3000

```js
node = await IpfsHttpClient('/ip4/127.0.0.1/tcp/5001')
orbitDB = await OrbitDB.createInstance(node)
```
this line is good, and i can get orbitDB.identity.id
however it received forbid error when trying to create the docs store
```js
history = await orbitDB.docs("history", {
  accessController: {
    write: ['*'],
}})
```

**Comment by thienpow** [comment]
```
"Access-Control-Allow-Origin": ["*"]
```

the only way to get it working
and only chromium based browser working... safari would fail

**Comment by geolffreym** [comment]
@thienpow which version you have of `secp256k1` please check in `node_modules/secp256k1/package.json`

**Comment by thienpow** [comment]
<img width="1108" alt="Screenshot 2020-07-14 at 4 11 21 AM" src="https://user-images.githubusercontent.com/9796623/87348936-22e6da00-c588-11ea-9114-69817e02c085.png">

3.8.0

**Comment by tabcat** [comment]
Hi @thienpow please try downgrading go-ipfs to parallel with https://github.com/orbitdb/orbit-db-test-utils/blob/e5becbf6ba414e91a465fb91c672930990191831/package.json#L24

**Comment by haydenyoung** [comment]
No further feedback. Closing.
