### ISSUE TITLE
When a database has a lot of data, db.load() will be very slow

### ISSUE THREAD

**Issue by mobeiqingkong** [orbitdb/orbitdb#824]
For example, when there are 34,978 pieces of data, the db.load() time is more than seven minutes
![6f955eb48279a7cd5ec7611f2e19365](https://user-images.githubusercontent.com/24273925/88122135-5bc32680-cbfa-11ea-859b-74d0155735c3.png)

**Comment by phillmac** [comment]
That's to be expected for that number of entries. Which store type are you using? If it's docstore perhaps you could look at using `putAll()` to reduce the round trip time to ipfs?

**Comment by mobeiqingkong** [comment]
This is my code
```javascript
async function _openDb(name, idField) {
    let db = await orbitdb.open(name, {
        accessController: {
            write: ['*']
        },
        type: 'docstore',
        create: true,
        indexBy: idField
    });
    await Promise.resolve(resolve => {
        db.events.on('replicated', resolve)
    })
    let startTimeFormat = moment().format();
    logger.debug(`Loading: ${name}，${startTimeFormat}`)
    let startTimeStamp = moment();
    await db.load();
    let endTimeFormat = moment().format();
    logger.debug(`Loading finished: ${name}, ${endTimeFormat}`)
    let endTimeStamp = moment();
    let time = endTimeStamp.diff(startTimeStamp, 'second');
    logger.debug(`Loading ${name} tooks ${time} second`)
    let dbInstance = {
        instance: db,
        lastVisit: new Date()
    };
    dbMap.set(name, dbInstance);
    return dbInstance;
}
```
When I load a database with 34968 records, it took 718 seconds. It's store type is docstore, This is my log
```
[2020-07-22T13:11:26.827] [INFO] app - all db loaded
[2020-07-22T13:11:44.092] [DEBUG] app - do query: 00000000-0000-0000-0000-000000000000-mocha-OneToMany_One {}
[2020-07-22T13:11:44.094] [DEBUG] app - loading db 00000000-0000-0000-0000-000000000000-mocha-OneToMany_One
[2020-07-22T13:11:44.171] [DEBUG] app - Loading: 00000000-0000-0000-0000-000000000000-mocha-OneToMany_One，2020-07-22T13:11:44+08:00
[2020-07-22T13:23:42.253] [DEBUG] app - Loading finished: 00000000-0000-0000-0000-000000000000-mocha-OneToMany_One, 2020-07-22T13:23:42+08:00
[2020-07-22T13:23:42.256] [DEBUG] app - Loading 00000000-0000-0000-0000-000000000000-mocha-OneToMany_One tooks 718 second
[2020-07-22T13:23:42.326] [DEBUG] app - found count 34968
```
![6f955eb48279a7cd5ec7611f2e19365](https://user-images.githubusercontent.com/24273925/88142486-28978c00-cc28-11ea-9fe9-0911187cc829.png)

**Comment by mobeiqingkong** [comment]
> That's to be expected for that number of entries. Which store type are you using? If it's docstore perhaps you could look at using `putAll()` to reduce the round trip time to ipfs?

When I use putAll to put data, and then use db.load(), the time is much shorter, but it still takes 26 seconds.

![6f955eb48279a7cd5ec7611f2e19365](https://user-images.githubusercontent.com/24273925/88161911-31498b80-cc43-11ea-8ba0-d2b0abc8d533.png)

**Comment by phillmac** [comment]
Yep. There's a few performace improvents in the pipline that _may_ improve this issue. For now that's pretty close to the best possible performance. Due to the simplistic way the index is updated, it slows down astronmicaly as more entries are added.

**Comment by kabo** [comment]
Could someone elaborate on why it has to be slow? I have keyvaluestore. My understanding is that it's just loading from the LocalStorage in my browser. That's normally very fast.
Also, is there any way to speed this up? I could imagine an option like "Only store a months worth of changes". Any change in the keyvaluestore older than that just gets reduced down to one entry, and the history before that gets lost. Any strategy like that in the works?

**Comment by tabcat** [comment]
@kabo 

> Any change in the keyvaluestore older than that just gets reduced down to one entry, and the history before that gets lost. Any strategy like that in the works?

This is similar to watermarking which is on the docket to be implemented in version 1. The trade is that using a snapshot of history brings in chances for conflicts in the future.

**Comment by kabo** [comment]
Ah, is that what watermark means? I was thinking of the type of watermark bills have, not high/low watermark. Cool, looking forward to v1 then :)

**Comment by tabcat** [comment]
Yes high/low watermark :smile:

**Comment by haydenyoung** [comment]
Closing but if problems persist with latest version, please re-open.

**Comment by koh-osug** [comment]
Was this closed because the initial load is now fast or was it closed although there haven't been an improvement? I.e. can it still take several minutes to load the data?
