### ISSUE TITLE
Using Chaos Mesh to enhance orbit-db's stability

### ISSUE THREAD

**Issue by zhouqiang-cl** [orbitdb/orbitdb#829]
Hello, I am [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) maintainer. Chaos Mesh is a open source chaos engineering platform for Kubernetes.

As you may have known, chaos engineering is a promising method that can guarantee system resilience in the database field. We have been practicing chaos engineering for long on databases and have found many issues in various fault scernarios (for example data consistency issue caused by excessive recovery time). Some of the issue records at https://github.com/orgs/chaos-mesh/projects/1. There are also [many adopters]( https://github.com/chaos-mesh/chaos-mesh#adopters) who are using Chaos Mesh to test their systems, such as PingCAP, Daily motion, Xpeng Motors, Meituan-Dianping, Apache pulsar, etc.

That said, I would like to invite you to use Chaos Mesh to enhance orbit-db's stability. You can directly use Chaos Mesh or integrate it with your test platform. Chaos Mesh supports rich injection methods, such as pod/container kill, network partition, network interruption, CPU/memory usage, time rollback, disk failure, etc.
Welcome to use it to enhance the stability of orbit-db. If you have any questions,  submit an issue at https://github.com/chaos-mesh/chaos-mesh, or send me an email zhouqiang@pingcap.com

Hope this helps and look forward to further communications. ❤️

**Comment by aphelionz** [comment]
Thanks for calling our attention to this :) We'll have a look soon.

**Comment by zhouqiang-cl** [comment]
> Thanks for calling our attention to this :) We'll have a look soon.

Thank you for your interest. If you have any problem, we are very pleasure if we can help

**Comment by zhouqiang-cl** [comment]
> Thanks for calling our attention to this :) We'll have a look soon.

Hi, @aphelionz may I ask have you already take a look at Chaos Mesh? If have, did you have any questions and requirements?

Thank you
