### ISSUE TITLE
Could not validate signature {"orbit-db": "^0.24.1"}

### ISSUE THREAD

**Issue by mobeiqingkong** [orbitdb/orbitdb#840]
{
    "orbit-db": "^0.24.1",
    "orbit-db-keystore": "^0.3.4",
    "orbit-db-storage-adapter": "^0.5.3"
}

I am using a document store for orbitdb with jsipfs. After I put some data, wher I load database, I get the following error.

![image](https://user-images.githubusercontent.com/24273925/93730953-8848ee00-fbfd-11ea-814f-0a9b225c87b2.png)

I created about 200 databases, most of them are normal, and there are about two abnormal.

**Comment by aphelionz** [comment]
Hi there, thanks for opening the issue.

Are you able to udpate to ipfs 0.50.2 and orbit-db 0.26.0? If so, does that solve the issue?

**Comment by mobeiqingkong** [comment]
> Hi there, thanks for opening the issue.
> 
> Are you able to update to ipfs 0.50.2 and orbit-db 0.26.0? If so, does that solve the issue?

When I use orbit-db@0.26.0, I catch new Error,  TypeError: Cannot read property 'length' of undefined.
![image](https://user-images.githubusercontent.com/24273925/93837436-aa537680-fcb8-11ea-86dd-771a589dc682.png)

I compare with  orbit-db@0.24.2,  orbit-db@0.24.2 did not have this problem. This error is in the package ipld-dag-cbor/util.js, function tarCID, 

![image](https://user-images.githubusercontent.com/24273925/93837616-69a82d00-fcb9-11ea-92b1-5a71cbb951b6.png)

When I use  orbit-db@0.24.2, cid.buffer is not undefined

![image](https://user-images.githubusercontent.com/24273925/93837646-90fefa00-fcb9-11ea-924e-4cdf579c302c.png)

but when I use orbit-db@0.26.0, cid.buffer is undefined, I use cid.bytes can resolve this problem

![image](https://user-images.githubusercontent.com/24273925/93837808-1a163100-fcba-11ea-879e-88c0f3c3cc77.png)

**Comment by aphelionz** [comment]
OrbitDB 0.26.0 is meant to be used with ipfs 0.50.2... what version of js-ipfs are you using?

What does `npm ls cids` tell you?

**Comment by mobeiqingkong** [comment]
> OrbitDB 0.26.0 is meant to be used with ipfs 0.50.2... what version of js-ipfs are you using?
> 
> What does `npm ls cids` tell you?


```
$ npm ls cids
hl-ipfs-agent@1.0.0 F:\project\hl\HL-ipfs-agent
+-- ipfs-http-client@44.3.0
| +-- cids@0.8.3
| +-- ipld-block@0.9.2
| | `-- cids@0.8.3  deduped
| +-- ipld-dag-cbor@0.15.3
| | `-- cids@0.8.3  deduped
| +-- ipld-dag-pb@0.18.5
| | `-- cids@0.8.3  deduped
| +-- ipld-raw@5.0.0
| | `-- cids@0.8.3  deduped
| `-- multiaddr@7.5.0
|   `-- cids@0.8.3  deduped
`-- orbit-db@0.26.0
  +-- cids@1.0.0
  +-- orbit-db-io@0.3.0
  | +-- cids@1.0.0
  | `-- ipld-dag-pb@0.20.0
  |   `-- cids@1.0.0  deduped
  `-- orbit-db-store@4.0.1
    `-- ipfs-log@5.0.0
      `-- ipfs-http-client@47.0.1
        +-- cids@1.0.0
        +-- ipfs-core-utils@0.4.0
        | `-- cids@1.0.0  deduped
        +-- ipld-block@0.10.1
        | `-- cids@1.0.0  deduped
        +-- ipld-dag-cbor@0.17.0
        | `-- cids@1.0.0  deduped
        +-- ipld-dag-pb@0.20.0
        | `-- cids@1.0.0  deduped
        +-- ipld-raw@6.0.0
        | `-- cids@1.0.0  deduped
        `-- multiaddr@8.0.0
          `-- cids@1.0.0  deduped

```
```
F:\>ipfs version
ipfs version 0.6.0
```
May be my ipfs version problem, let me use ipfs@0.50.2 to test

**Comment by aphelionz** [comment]
Ah, it's your `ipfs-http-client`! Update that to 47.x.x and you should be good to go.

**Comment by mobeiqingkong** [comment]
> Ah, it's your `ipfs-http-client`! Update that to 47.x.x and you should be good to go.


Yep,  after update `ipfs-http-client`, I resolve the typeError. thank :)  
But I don’t know if the signature error will still appear after the update.
Emm, I continue to test

**Comment by aphelionz** [comment]
Any validation errors pop up yet? :)

**Comment by mobeiqingkong** [comment]
> Any validation errors pop up yet? :)
I encountered this problem again today
```
{
  "message": "Could not validate signature \"3044022042010ad2a178d5b0861dc2a8e29464d061984aabff1ed3b25a638982679f6ff4022038fa1c9dc6dcd9484e1822af00e20039016422f8656629c48af128ac37834a66\" for entry \"zdpuAssYBSEsYK9b56zdzNZ6hmxUJyxexZ8uydh4vqKyswZ6B\" and key \"041f11f0ea2a9951c3347f00b1720d04a25fb543284615f36e1ea00610bc39fbd47311c8bce299fda024ff75a17a5ad3dc9c88aef1b33d8bccb2f17d0633b8b089\"",
  "stack": "Error: Could not validate signature \"3044022042010ad2a178d5b0861dc2a8e29464d061984aabff1ed3b25a638982679f6ff4022038fa1c9dc6dcd9484e1822af00e20039016422f8656629c48af128ac37834a66\" for entry \"zdpuAssYBSEsYK9b56zdzNZ6hmxUJyxexZ8uydh4vqKyswZ6B\" and key \"041f11f0ea2a9951c3347f00b1720d04a25fb543284615f36e1ea00610bc39fbd47311c8bce299fda024ff75a17a5ad3dc9c88aef1b33d8bccb2f17d0633b8b089\"\n    at verify (/opt/OPSDATA/app/IPFS/HL-ipfs-agent/node_modules/ipfs-log/src/log.js:414:27)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at runNextTicks (internal/process/task_queues.js:66:3)\n    at processImmediate (internal/timers.js:429:9)\n    at async pMap.concurrency (/opt/OPSDATA/app/IPFS/HL-ipfs-agent/node_modules/ipfs-log/src/log.js:420:7)"
}
```
and that is my version
```
$ npm ls cids
hl-ipfs-agent@1.0.0 F:\project\hl\HL-ipfs-agent
+-- ipfs-http-client@47.0.1
| +-- cids@1.0.0
| +-- ipfs-core-utils@0.4.0
| | `-- cids@1.0.0  deduped
| +-- ipld-block@0.10.1
| | `-- cids@1.0.0  deduped
| +-- ipld-dag-cbor@0.17.0
| | `-- cids@1.0.0  deduped
| +-- ipld-dag-pb@0.20.0
| | `-- cids@1.0.0  deduped
| +-- ipld-raw@6.0.0
| | `-- cids@1.0.0  deduped
| `-- multiaddr@8.0.0
|   `-- cids@1.0.0  deduped
`-- orbit-db@0.26.0
  +-- cids@1.0.0
  +-- orbit-db-io@0.3.0
  | +-- cids@1.0.0
  | `-- ipld-dag-pb@0.20.0
  |   `-- cids@1.0.0  deduped
  `-- orbit-db-store@4.0.1
    `-- ipfs-log@5.0.0
      `-- ipfs-http-client@47.0.1
        +-- cids@1.0.0
        +-- ipfs-core-utils@0.4.0
        | `-- cids@1.0.0  deduped
        +-- ipld-block@0.10.1
        | `-- cids@1.0.0  deduped
        +-- ipld-dag-cbor@0.17.0
        | `-- cids@1.0.0  deduped
        +-- ipld-dag-pb@0.20.0
        | `-- cids@1.0.0  deduped
        +-- ipld-raw@6.0.0
        | `-- cids@1.0.0  deduped
        `-- multiaddr@8.0.0
          `-- cids@1.0.0  deduped

```
![image](https://user-images.githubusercontent.com/24273925/94238866-88215900-ff43-11ea-9c3e-c3150f27dc1e.png)

**Comment by tabcat** [comment]
Im wondering if this is related to https://github.com/orbitdb/orbit-db/issues/868

**Comment by haydenyoung** [comment]
Closing for now. If this issue still persists after upgrading to v1, feel free to re-open.
