### ISSUE TITLE
Orbitdb Replication

### ISSUE THREAD

**Issue by kottackalsulvin** [orbitdb/orbitdb#844]
Hi,
I am trying to replicate my orbitdb in another browser using the below address

`const db= await orbitdb.docs('orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com');`

If I try to open this address in a new tab in the same browser,then it can be accessible. But in another browser,it is not accessible. Am getting an orbit db ‘id’ as below, when am using the above address in another browser.

`id: "/orbitdb/zdpuB37ifQdj2RVmBqyxpauYJDU2xUvDKUZpuMgeSYham6jps/orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com"`

I have tried to connect using ipfs.connect.swarm but nothing changed.

In browse A, tried the below code:

```
const info=await ipfs.id()
console.log("IPFS node ready with id:"+info.id); 
```
And in browser B, tried the below code:

```
ipfs = new IPFSS({
start: true, 
EXPERIMENTAL: {
pubsub: true
},
preload: { 
enabled: false 
},
config: {
Addresses: {
Swarm: [
'/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
]
}
}
})


ipfs.on('ready', async () => {
await ipfs.swarm.connect('/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/ipfs/QmVcoer53vBab2mkzgf2F71U8Xn5SEEKFd5hrqqazvr7oN')

const identity = await Identities.createIdentity({ id: 'local-id' })

const orbitdb = await OrbitDB.createInstance(ipfs, { identity: identity })

const defaultOptions = { accessController: { write: [orbitdb.identity.id] }}

const docStoreOptions = {
defaultOptions,
indexBy: 'msg',
}

const store = await orbitdb.docs('orbitdb/zdpuAomVC6YbN11jjtkZHqrLxLHbsQd5LS5v7woJU8weZhbcG/Tom jane@gmail.com',docStoreOptions);
store.load();
console.log(store);
})

```
**Environment**

Npm: 6.13.4
Node: 10.19.1
libp2p : 0.26.2
libp2p-webrtc-star: 0.13.2
libp2p-websockets: 0.12.2

**Comment by kottackalsulvin** [comment]
Please help me to resolve this issue.

**Comment by kottackalsulvin** [comment]
![Screenshot from 2020-10-22 01-09-24](https://user-images.githubusercontent.com/40980270/97113117-40dae380-170e-11eb-82bf-e362932785a9.png)

**Comment by kottackalsulvin** [comment]
Anyone have any idea?

**Comment by dysbulic** [comment]
The error is, "Non-base58 character". There's a space before `jane@gmail.com` in what you're trying as the address.

Omit the space and everything after.

**Comment by tabcat** [comment]
@kottackalsulvin is this resolved?

**Comment by tabcat** [comment]
This seems looks very strange `"/orbitdb/zdpuB37ifQdj2RVmBqyxpauYJDU2xUvDKUZpuMgeSYham6jps/orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com"`

its encapsulating another orbitdb address inside the name of an orbitdb address. this is happening somehow because a method thinks a parameter is a name for a new db and not the existing db address to open.

**Comment by kottackalsulvin** [comment]
@tabcat no it's not resolved. @dysbulic it's not because of the space before 'jane@gmail.com', I removed it but nothing changed.

**Comment by phillmac** [comment]
orbitdb.docs Should be orbitdb.open

**Comment by tabcat** [comment]
according to the API docs, `.docs` should accept addresses https://github.com/orbitdb/orbit-db/blob/master/API.md#orbitdbdocsnameaddress-options and the [source for `.docs`](https://github.com/orbitdb/orbit-db/blob/68971f4ad8e0d414fc6c57eec1401e774bc78d43/src/OrbitDB.js#L156-L159), at least currently, uses `.open` directly with no changes on the address parameter.

**Comment by tabcat** [comment]
I think the issue has to do with the input address being invalid because of the example:
> const db= await orbitdb.docs('orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com');

the address according to the OrbitDbAddress class should start with '/orbitdb' not 'orbitdb'
https://github.com/orbitdb/orbit-db/blob/68971f4ad8e0d414fc6c57eec1401e774bc78d43/src/orbit-db-address.js#L20

**Comment by phillmac** [comment]
I think the api docs  may be a bit misleaading,
Doesn't this line forcibly create a new db ever
