### ISSUE TITLE
Transport over IOTA streams

### ISSUE THREAD

**Issue by dysbulic** [orbitdb/orbitdb#845]
I'm currently participating in the [Integrate Everything with IOTA Hackathon](//hackathon.iot2tangle.io). The requirement is that your entry must utilize [IOTA Streams](https://www.iota.org/solutions/streams) for data transfer and IOTA for payment.

I really like IOTA. I think that Tangles are unarguably more energy efficient than Blockchains. I have been working on an [ad hoc courier dApp](//pkg.dhappy.org) for a couple weeks. Currently it is backed by Ethereum, specifically [3box.io](3Box) which provides a persistent identity service and encrypted CRDT-backed data stores.

Streams is in Rust, but they've recently come out with a [HTTP gateway](//github.com/iot2tangle/Streams-http-gateway/). I can POST JSON to add it to a Stream.

My understanding of OrbitDB is that it is serializing a blockchain of Conflict-Resistant operations to IPFS and advertising the head via PubSub. My question is as to the feasibility of using Streams as an alternative transport and storage mechanism.

The main issue I see if the size of the data payloads. I don't know what to expect from OrbitDB and I don't know what Streams can reasonably handle.

Is my understanding that there's a set of files saved to IPFS that, if small enough, could live in the Tangle correct?

**Comment by aphelionz** [comment]
Great question! This was answered in another issue here: https://github.com/orbitdb/orbit-db/issues/842#issuecomment-716988099

It seems like there's a lot of interest in alternatives to the pubsub mechanism, which is great :+1:

**Comment by kuhlmannmarkus** [comment]
Is there really a need for decentralized databases on DLTs? I mean, the DLT itself is already a (temporary) database.

**Comment by dysbulic** [comment]
> Is there really a need for decentralized databases on DLTs? I mean, the DLT itself is already a (temporary) database.

The data persisted through IOTA Streams is immutable. I need some mechanism for updating state and CRDTs seem like the perfect fit.

The question is whether putting the conflict-resistant operations on the Tangle will be efficient. If so, they get the advantage of Streams' encryption and I can easily create serverless private databases.

**Comment by kuhlmannmarkus** [comment]
Data on the IOTA tangle is immutable only until a snapshot. How long do you want to be able to access the data?

**Comment by dysbulic** [comment]
> Data on the IOTA tangle is immutable only until a snapshot. How long do you want to be able to access the data?

That was one of the main reasons I moved off IOTA when I was reconsidering it before.

The solution, apparently, will be running a permanode to preserve and make available specific transactions (or a "pinning" service that serves the same function).

**Comment by haydenyoung** [comment]
Closing as probably out-of-date now but feel free to re-open if still relevant.
