### ISSUE TITLE
Solid Storage

### ISSUE THREAD

**Issue by EisenbergEffect** [orbitdb/orbitdb#863]
I'm curious if building a [solid](https://inrupt.com/solid) storage implementation has been considered for OrbitDB (instead of IPFS). Is there any documentation on how to implement and plug something like that in?

**Comment by tabcat** [comment]
Hi @EisenbergEffect thank you for bringing this up. To my knowledge this has not been considered, but members in the community have suggested making extensions like this much easier. As I don't know how solid storage works I cannot tell how much change or what changes this would require to make possible. Most if not all of the io with IPFS has been abstracted into [orbit-db-io](https://github.com/orbitdb/orbit-db-io) which could make swapping out the storage simple if it is content addressed. However Orbit-db also relies on the passed IPFS instances pubsub to replicate updates.
I would be happy to discuss specifics/constraints of solid storage and orbit-db with you in our [community chat](https://gitter.im/orbitdb/Lobby) as well as trade materials related to this if you are interested.
