### ISSUE TITLE
Any Graph DB implementations?

### ISSUE THREAD

**Issue by Outstep** [orbitdb/orbitdb#864]
Hi All,

I am new to IPFS and OrbitDB but it seems to have a lot of great potential for a project, or two that I am working on now.

One thing that I am greatly interested in is handling and working with large graph databases and I am wondering if OrbitDB can be make to do anything in this regard?

I seem to have read somewhere in my browsing around that OrbitDB can be customized for a different datastore and am curious if anyone has tried to implement a Graph db variant for OrbitDB that utilizes IPFS as this would be exactly what I am looking to locate, if at all possible.

Any information or suggestions would be greatly appreciated.
Cheers and Thanks in advance.

**Comment by jeffkhull** [comment]
Hi @Outstep , I was wondering the same thing.  I'm just starting out trying to create a semantic linked data browser (design will be stored [here]( https://github.com/WorldGraph/worldgraph-design)) and am wondering how one might store and traverse semantically linked data in  IPFS.

**Comment by tabcat** [comment]
https://github.com/moskalyk/orbit-db-graphstore

**Comment by CSDUMMI** [comment]
@Outstep you might want to read this new part of the Field Manual, if you want to develop your
own Graph DB. [Customizing OrbitDB](https://github.com/orbitdb/field-manual/blob/main/05_Customizing_OrbitDB/00_Introduction.md)

**Comment by haydenyoung** [comment]
Closing as previous comment appears to answer the issue raised.
