### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by nichoth** [orbitdb/orbitdb#873]
Have been following along with the readme, but i get stuck at this step -- https://github.com/orbitdb/orbit-db#module-with-ipfs-instance .

The 'replicated' event never happens

```js
// Listen for updates from peers
  db.events.on("replicated", address => {
    console.log(db.iterator({ limit: -1 }).collect());
  });
  ```
  
  This is my repo for the demo app -- https://github.com/nichoth/orbit-demo/blob/main/src/index.js#L23

**Comment by tabcat** [comment]
This often happens when the two ipfs nodes are not able to communicate. Here is a testing library we use that includes minimal ipfs configuration for nodejs instances to talk.

make sure ipfs is listening on an interface: https://github.com/orbitdb/orbit-db-test-utils/blob/3e2977d9e7772cadcc48581d75af24a8105d03af/config/node.js#L7-L31
regarding this chunk of code, your primarily concerned with options.config.Addresses.swarm and you can just use localhost addr instead of wildcard ip

connect two ipfs instances: https://github.com/orbitdb/orbit-db-test-utils/blob/master/connect-peers.js

**Comment by nichoth** [comment]
Thank you. I've repeated the setup, but was confused by

> you can just use localhost addr instead of wildcard ip

regarding https://github.com/orbitdb/orbit-db-test-utils/blob/3e2977d9e7772cadcc48581d75af24a8105d03af/config/node.js#L7-L31

The given example is

```js
config: {
      Addresses: {
        API: '/ip4/127.0.0.1/tcp/0',
        Swarm: ['/ip4/0.0.0.0/tcp/0'],
        Gateway: '/ip4/0.0.0.0/tcp/0'
      },
```
So what do i want to put the the `swarm` address?

Thank you

**Comment by phillmac** [comment]
If you are running two ipfs instances on the same computer, 127.0.0.1
If its two computers on the same network,
Then you will need to use the computer's  networ ip
E.G. 192.168.1.5 & 192.168.0.10

**Comment by nichoth** [comment]
thank you. so i have

```js
                Addresses: {
                    API: '/ip4/127.0.0.1/tcp/0',
                    Swarm: ['/ip4/127.0.0.1/tcp/0'],
                    Gateway: '/ip4/0.0.0.0/tcp/0'
                },
```

and there's a new error -- `Error: no valid addresses were provided for transports [WebSockets,WebRTCStar,Circuit]`

![image](https://user-images.githubusercontent.com/5776508/113092944-d853cf00-91a3-11eb-9bc0-e804acdb9684.png)

**Comment by phillmac** [comment]
The /tcp/ transport isn't available in the browser.
I don't know what the current best webrtc star afldress is to use, but maybe someone else xan answer

**Comment by tabcat** [comment]
He is an [example for browsers](https://github.com/orbitdb/orbit-db/blob/68971f4ad8e0d414fc6c57eec1401e774bc78d43/examples/browser/example.js#L48-L72).

**Comment by nichoth** [comment]
Progress, but still errors :(

`Error: peer is not available` when using the new config

https://github.com/nichoth/orbit-demo/blob/ed186740a2c2533476896af52b5a275b309e01b7/src/index.js

![image](https://user-images.githubusercontent.com/5776508/113350265-1826cd80-92ee-11eb-866a-52962b931ffd.png)

```js
return await IPFS.create({
            pubsub: true,
            EXPERIMENTAL: { pubsub: true },
            config: {
                Addresses: {
                    API: '/ip4/127.0.0.1/tcp/0',
                    Swarm: [
                        // '/ip4/127.0.0.1/tcp/0',
                        '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
                        '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
                        '/dns4/webrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/',
                    ],
                    Gateway: '/ip4/0.0.0.0/tcp/0'
                },
            },
            repo: "./path-for-js-ipfs-repo"
        })
```

thanks for all the help

**Comment by phillmac** [comment]
I've run into this several times, It's not something I've been able to fix however.
I had slightly more success running my own private webrtc star server, but at the end of the day it still doesn't work
If anyone has a fix for this I'd much appreciate it

**Comment by tabcat** [comment]
@nichoth try removing the `.config.Addresses`'s `.API` and `.Gateway` properties

**Comment by nichoth** [comment]
I tried with no `API` or `Gateway` -- https://github.com/nichoth/orbit-demo/blob/main/src/index.js#L42 .  It seems like something different would happen nearly every time i refreshed the page 🤷 

```js
config: {
                Addresses: {
                    // API: '/ip4/127.0.0.1/tcp/0',
                    Swarm: [
                        // '/ip4/127.0.0.1/tcp/0',
                        '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
                        '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
                        '/dns4/webrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/'
                    ],
                    // Gateway: '/ip4/0.0.0.0/tcp/0'
                },
            },
```

--------------------------------

The first time I ran it:
```
Uncaught (in promise) AggregateError: 
    Error: The operation was aborted
```
![image](https://user-images.githubusercontent.com/5776508/113482596-36a6d900-9454-11eb-8370-3f6395737d7d.png)

-----------------------------------------

The next time:
```
Uncaught (in promise) AggregateError: 
    Error: peer is not available
```
![image](https://user-images.githubusercontent.com/5776508/113482585-2b53ad80-9454-11eb-8cb4-9091ab6ad5c9.png)

-----------------------------------------

The third time it seemed to work
![image](https://user-images.githubusercontent.com/5776508/113482578-1ecf5500-9454-11eb-8742-c0bbf04d4a67.png)

-----------------------------------

Fourth time
```
Uncaught (in promise) AggregateError: 
    Error: peer is not available
```
![image](https://user-images.githubusercontent.com/5776508/113482572-1414c000-9454-11eb-9c25-203e514b728d.png)

--------------------------------------------------

Next a new error
```
Uncaught (in promise) TypeError: this.events.off is not a function
```

![image](https://user-images.githubusercontent.com/5776508/113482562-07906780-9454-11eb-9d7c-97a4709f3638.png)

**Comment by phillmac** [comment]
The error 
```
Uncaught (in promise) AggregateError: 
    Error: peer is not available
```
Is definitely a bug in js-ipfs as far as I can see.
However `TypeError: this.events.off is not a function` is something in orbit db for sure. Does it do it regularly?
How often?

**Comment by nichoth** [comment]
@phillmac it is irregular, it seems totally random if it throws an error or works

**Comment by tabcat** [comment]
this ipfs config is persisted so u need to clear the indexeddb data for that site to reset it.

**Comment by haydenyoung** [comment]
Closing as out-dated. Feel free to re-open if the problem persists with version 1.
