### ISSUE TITLE
No Documentation for Access Controllers in API.

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbitdb#881]
The API.md document should be a full and 
complete documentation of the API. 

But it does not have a section on Access Controllers,
which is a serious omission.

It even refers back to the GUIDE.md File for Documentation
for Access Controllers, which just makes for a mess of tabs for the developers:  
https://github.com/orbitdb/orbit-db/blob/master/API.md#orbitdbcreatename-type-options

**Comment by haydenyoung** [comment]
Hopefully https://github.com/orbitdb/orbitdb/blob/main/docs/ACCESS_CONTROLLERS.md provides some clarification and direction. If not, please feel free to re-open this issue for further discussion.
