### ISSUE TITLE
Upgrade js-ipfs -> private-ip versions < 2.0.0 are vulnerable to SSRF attacks

### ISSUE THREAD

**Issue by EmiM** [orbitdb/orbitdb#882]
Two weeks ago github informed that private-ip (used in libp2p-utils) is vulnerable to SSRF attacks: https://github.com/advisories/GHSA-43ch-2h55-2vj7

Js-libp2p-utils bumped private-ip in version 0.2.3 https://github.com/libp2p/js-libp2p-utils/compare/v0.2.2...v0.2.3
OrbitDb still supports js-ipfs versions <= 52 with older libp2p and libp2p-utils.

```
└─┬ ipfs@0.52.3
  └─┬ ipfs-core@0.3.1
    └─┬ libp2p@0.29.3
      └─┬ libp2p-utils@0.2.1
        └── private-ip@1.0.5
```

Perhaps a workaround for projects using orbit-db is to force newest version of private-ip. I didn't see any code changes connected with upgrading private-ip in libp2p so it may just work without any problems.
If it would be the case maybe orbit-db could also force the secure version of private-ip - until it supports the newer js-ipfs?

**Comment by haydenyoung** [comment]
Closing as possibly out-dated.
