### ISSUE TITLE
Should I be able to rebuild my database if all nodes go offline?

### ISSUE THREAD

**Issue by devdevgoat** [orbitdb/orbitdb#884]
Apologies if I missed this in the FAQ/issues log, but I can't find anything that clearly answers this question as everything seems to say 'make sure one node is available/accessible'.

My understanding of using IPFS as the backend was that the persisted IPFS data could be used to reconstruct a new master node by loading up the orbitdb address, is that not the case? 

Thanks for the help!
Russ

**Comment by aphelionz** [comment]
Thanks for this issue - it can rebuilt _so long as the IPFS data are pinned somewhere in the IPFS network._ If all the other peer nodes are offline, then you run the risk of not being able to.

Most projects use separate pinning nodes for this.

**Comment by rlamb2** [comment]
Any links to IPFS pinning and/or functions I should use for this process? Would I use a pin to download the files to a repo folder before initializing the instance?

**Comment by rlamb2** [comment]
Ok, readup on pinning. Feel pretty good about understanding it, but still at a lost for how to get orbitdb to load up existing data from pinned content.  Any help here is greatly appreciated!

**Comment by phillmac** [comment]
You'd need to inject a heads message into the pubsub heads replication module.
I don't think this is easily done right now, there's no exposed functions in the api so it would mean either poking around in the private properties and workings, or rolling your own broker and injecting it into `OrbitDB.createInstance()`

**Comment by aphelionz** [comment]
You could use this: https://github.com/orbitdb/orbit-db-pinner
