### ISSUE TITLE
In code documentation

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbitdb#888]
Using documentation inside the source code
has the advantage, that the documentation
will change more as the source code does.
(We'll still have to make sure it does, but it's easier to find the relevant docs for your piece of code).

I propose using [sphinx-js](https://github.com/mozilla/sphinx-js) and using
this repository as a test case for this documentation system, since
the source code here is most easily documented and 
thus not much time will be spent on actually working out the documentation,
while still figuring out the system.

I have talked about this documentation already in a [PR on the welcome repo](https://github.com/orbitdb/welcome/pull/97).

And I am working on my fork of this repository already to setup sphinx-js: [CSDUMMI/orbit-db](https://github.com/CSDUMMI/orbit-db/tree/master)

**Comment by haydenyoung** [comment]
Hopefully the new API https://api.orbitdb.org/ will provide more clarity.
