### ISSUE TITLE
Relations with docstore?

### ISSUE THREAD

**Issue by Faares** [orbitdb/orbitdb#896]
Hi, 
First of all, let me express my sincere appreciation for your awesome work!

Recently, I started to think about using `orbit-db` in one of my projects, but the project needs some relations e.g. `one to one`, `one to many` ..etc between two tables at least. I know I can do it manually by adding a new field..etc but! what about the queries? is there native support for such as this? again, I can perform it by more than one query.. but I prefer to use `JOIN`s to accomplish these tasks. 

Regards.

**Comment by haydenyoung** [comment]
If your application needs relationships and you need to query your data based on those relationships, a relational db is probably a better solution. If you are looking for a decentralized solution, say you want to deploy a db with your dapp and want users to be able to run it across multiple machines, OrbitDB is ideal. If you also need to crunch some data, perhaps integrating some kind of 3rd party db or other indexing tool (say, Solr server) might be required. However, this would require a more complex software architecture.

The first question, though, is, what kinds of data are you looking to store and how does your querying requirements fit in to your use case.
