### ISSUE TITLE
Wildcard query on store for autocompletion

### ISSUE THREAD

**Issue by kimgysen** [orbitdb/orbitdb#897]
I need to store between 7k and 8k tags in the database, which the user can access through autocompletion from the frontend.  
Is there a straightforward way through the api in which wildcard queries can be achieved? 

Example: 'orb%'

**Comment by kimgysen** [comment]
Looks like something could be done using a substring, as shown in the docs: 

`const all = db.query((doc) => doc.followers >= 500)`

**Comment by haydenyoung** [comment]
Closing but I'm going to leave a reference to https://github.com/orbitdb/orbitdb/issues/438.

Perhaps this can be re-opened or addressed in a later version of OrbitDB using a new issue.
