### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by gdethier** [orbitdb/orbitdb#905]
Currently, one wanting to use orbit-db's API in a TypeScript project must provide type definitions (him/her)self. It would be nice to be able to install type definitions with `yarn add --dev @types/orbit-db` or something the like.

**Comment by chrispanag** [comment]
There is semi-official type support here: 

https://github.com/orbitdb/orbit-db-types

Just add `"@types/orbit-db": "https://github.com/orbitdb/orbit-db-types.git"` to your `package.json`

**Comment by gdethier** [comment]
Great, thanks for the link @chrispanag ! I guess the issue should remain open until type support becomes official, right?

**Comment by chrispanag** [comment]
You are welcome @gdethier! 

> I guess the issue should remain open until type support becomes official, right?

This is up to the maintainers. Adding typings to OrbitDB was also mentioned on the [Road to v1.0 Thread](https://github.com/orbitdb/orbit-db/issues/819#issuecomment-774845639).

**Comment by arseniy-gl** [comment]
I propose going to typescript.

My first step in [project orbit-db-io](
https://github.com/orbitdb/orbit-db-io/pull/36)

**Comment by haydenyoung** [comment]
Currently there are no plans to migrate OrbitDB to TS. However, there are contributions being proposed which provide type defs.
