### ISSUE TITLE
Proposal for two pull requests

### ISSUE THREAD

**Issue by julienmalard** [orbitdb/orbitdb#906]
I wanted to ask whether the following ideas for pull requests would be welcomed:

1. I see that Orbit-DB caches opened stores in `this.stores[address]` but, if I understand correctly, it does not use this cache when the same DB is requested again. In my own code, when two parts of the code requested the same DB, this led to two unique open instances of the same DB that did not sync correctly with each other. I implemented my own caching mechanism, but perhaps this would be better implemented at the Orbit-DB instance level?
2. As far as I can see, `close()` is never called on a DB's access controller when the DB is closed. Could this be added to the orbit-db-store `close()` method?

Thanks!

**Comment by aphelionz** [comment]
#2 definitely sounds like it is a bug and should be fixed.

#1 might be better expressed as an SCP? https://github.com/orbitdb/SCPs

**Comment by phillmac** [comment]
Something like this would be useful imo.
I'm using this in the http api:
https://github.com/phillmac/orbit-db-managers/blob/develop/src/DBManager.js
If you want to formally specify an interface as a SCP I'm 1000% down to make a compliant implementation

**Comment by julienmalard** [comment]
No. 1 is now proposed in https://github.com/orbitdb/SCPs/pull/10.
Please let me know what you think!

**Comment by tabcat** [comment]
an overview implementation for 1. in my mind would be to use the db addresses as keys for an object containing unresolved databases and return `this.stores[<db address>]` or `this.<object of unresolved databases>[<db address>]`.

**Comment by julienmalard** [comment]
@tabcat I'm not sure I understand - what do you mean by unresolved databases? I was thinking that only opened databases would be added to `this.stores`...

**Comment by tabcat** [comment]
it would be a separate object that would hold unresolved database promises until they are resolved so concurrent calls to .create would return the same database.
