### ISSUE TITLE
In-browser examples/tutorials

### ISSUE THREAD

**Issue by glensimister** [orbitdb/orbitdb#907]
Hi

After finding out that the Brave browser is now supporting IPFS, I decided to look into IPFS and OrbitDB to see if it suitable for a browser extension I was playing around with a while back. However, after looking at the docs I noticed there wasn't much info about how to use OrbitDB in the browser. 

I looked at the browser example, but it seems incomplete.  https://github.com/orbitdb/orbit-db/tree/main/examples/browser
I also looked at the following thread and followed the instructions, but npm install failed. https://github.com/orbitdb/orbit-db/issues/403

Are there any examples that will help me experiment with a very basic CRUD app on IPFS?

While i'm here, do you think OrbitDB/IPFS would be suitable for the extension that I want to build? Here is a video demonstration: https://www.youtube.com/watch?v=9lG37usSwoo 

The purpose of the extension is enable people to like, dislike and comment on webpages (or anything for that matter).  I'm also interested in the possibility of using IPFS for personal data stores (similar to the Solid project), where the browser plugin exposes an API which other apps can interact with. I've got lots of ideas but I first need to decide which stack to use. 

Thanks

**Comment by julienmalard** [comment]
Hello,

Sorry for the late comment...hope this is still of use to you. [Constellation](https://github.com/reseau-constellation/constellation) is an example project of mine that works in the browser and also Electron.

Hope this helps! Documentation is still pending so feel free to contact me if you'd like to discuss further.

**Comment by haydenyoung** [comment]
Not sure if you reached out to @julienmalard on this issue but feel free to re-open if you would like to discuss your use case further.
