### ISSUE TITLE
Using of OrbitDB

### ISSUE THREAD

**Issue by CryptoGraph929** [orbitdb/orbitdb#910]
Our team is planning to build the game.
This game will be built for windows and android users, So we want to know if OrbitDB supports this type of project so that we can store our game score data in the OrbitDB database.

**Comment by CSDUMMI** [comment]
In general, OrbitDB is not dependant on a specific OS. 

Whether it fits into your project though is a little more complicated than that.

Some factors that you might want to consider are:
1. How sensitive is your data? I.e. Are there potential privacy problems to come up when publishing "game scores" in a publicly readable database?
2. Why are P2P Databases more suited to your application than traditional centralized applications? 
3. How stable should your software be? OrbitDB is a software in the alpha stage of development. Many breaking changes should be expected as development continues. 
(See [The Road to 1.0](https://github.com/orbitdb/orbit-db/issues/819))
If you want to rely on OrbitDB for a long term stable product, you probably should look elsewhere for now.

But theoretically any kind of JSON Object or Binary Object can be stored and replicated in an OrbitDB database. Look at the [store section of the API documentation](https://github.com/orbitdb/orbit-db/issues/819) for a suitable 
database for your use case. 

I hope this to be helpful.

**Comment by CSDUMMI** [comment]
@CryptoGraph929 can this be closed?

**Comment by haydenyoung** [comment]
Closing.
