### ISSUE TITLE
await orbitdb.keyvalue(anotherkvdb.address) not returning any result

### ISSUE THREAD

**Issue by xavicolomer** [orbitdb/orbitdb#919]
Hi there,

I created a database like so:

```
const ipfs = await IPFS.create({
      repo,
      start: true,
      preload: { 
        enabled: false
      },
      EXPERIMENTAL: {
        pubsub: true,
      },
      config: {
        Addresses: {
          Swarm: [
            '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
            '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/',
            '/dns4/webrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/',
          ]
        },
      }
    })

    console.log('ready', repo, address);
  
    const orbitdb = await OrbitDB.createInstance(ipfs);

let db = await orbitdb.docs('name', {
      create: true, 
      overwrite: false,
      localOnly: false,
      type: 'keyvalue',
      accessController: {
        write: ['*'],
      }
    })
```

then I got the address by:

`db.address.toString()`

Finally, from another user I am trying to open this database like so:

`db = await orbitdb.keyvalue(address)`

But await never finishes, and there are no errors in the console.

I have other databases (readonly) and all work fine.

Any idea / suggestion?

Thanks!

**Comment by tabcat** [comment]
The manifest in the address is not able to be fetched, this most likely means a connectivity issue between the ipfs nodes. We are likely to change the api a bit to make this more clear (and probably add an informative console message). Feel free to join the [community chat](https://riot.im/app/#/room/#orbit-db:matrix.org) for trouble-shooting.

**Comment by CSDUMMI** [comment]
Also: You no longer need to provide `EXPERIMENTAL` as an option to js-ipfs. PubSub is enabled by default.

**Comment by tabcat** [comment]
@CSDUMMI please keep things on topic in issues/pulls.

**Comment by haadcode** [comment]
Hi @xavicolomer 👋

I believe this line:
`let db = await orbitdb.docs(…`

should be:
`let db = await orbitdb.kv(…`

That is, docs databases can’t be opened as keyvalue databases.

let us know if this solves your issue.

**Comment by CSDUMMI** [comment]
If that was the issue here, the `let db = await orbitdb.keyvalue` should throw an error, not do nothing:
```
Uncaught:
Error: Database '/orbitdb/zdpuAmVqutwmc8UVJ8gkGo89AekHgZAjAFnpTdA7TgcMagGmx/abc' is type 'docstore' but was opened as 'keyvalue'
    at OrbitDB.open ($HOME/orbit-discussion/node_modules/orbit-db/src/OrbitDB.js:452:65)
```

**Comment by tabcat** [comment]
It's possible the manifest is not being resolved from the address which would hide the second issue of trying to open a docstore as a keyvalue store.

**Comment by CSDUMMI** [comment]
If that is the case, shouldn't there be some timeout triggered?

**Comment by vinch** [comment]
I have the exact same issue. Were you able to solve it @xavicolomer?

**Comment by ilovelili** [comment]
any update on this one? I also failed on `const manifest = await io.read(this._ipfs, dbAddress.root, { timeout: options.timeout || defaultTimeout }) `

**Comment by haydenyoung** [comment]
Please test with latest version. If problem persists, feel free to re-open the issue.

**Comment by ilovelili** [comment]
omg i got the answer after one year...
