### ISSUE TITLE
Everyone can write, but only himself and db creator can read, is it possible?

### ISSUE THREAD

**Issue by shareworlds** [orbitdb/orbitdb#920]
Everyone can write, but only himself and db creator can read, is it possible?
himself can read his record,
db creator can read all records,

**Comment by CSDUMMI** [comment]
Not yet with OrbitDB.

**Comment by julienmalard** [comment]
A bit late, but I think you might be able to use local-web-first/auth to make this work. You could have anyone be allowed to encrypt data that can only be read by the "admin" (or anyone else, for that matter) of a local-web-first/auth team. Though this would require you to manage two sets of identity - one built-in with OrbitDB for managing write access, and another through local-web-first/auth to manage read access.

**Comment by julienmalard** [comment]
...and since OrbitDB is public, if anyone's auth keys are leaked, then there is next to no chance of ever being able to recall the now-decryptable data stored in the database.
