### ISSUE TITLE
orbit-db performance test

### ISSUE THREAD

**Issue by alvin-reyes** [orbitdb/orbitdb#930]
# Proposal
In order to help evaluate orbit-db, we need to have some regression or performance test that will justify the use of orbit-db as a distributed storage technology. 

# Build tests that will show

- Database Throughput. 
- Database Response or Latency. 
- Database Connections. 

This is purely just a suggestion.

**Comment by haydenyoung** [comment]
A number of [benchmarks](https://github.com/orbitdb/orbitdb/tree/main/benchmarks) have been added to the OrbitDB project and additional benchmarks are welcome.
