### ISSUE TITLE
Starting IPFS... Uncaught bundle.js:70:30204

### ISSUE THREAD

**Issue by slrslr** [orbitdb/orbitdb#935]
Hello, in Firefox 93.0 i can see the following error:
![orbitdbuncaughtbundlejs](https://user-images.githubusercontent.com/6596726/138859285-31fa1100-df0a-4f04-97de-ffe04d6f9b60.png)
(Uncaught bundle.js:70:30204)
I am using IPFS companion 0.9.1/dc2715a go-ipfs
Note that i have not installed any orbitdb software.

**Comment by slrslr** [comment]
So developers here (beside tabcat) thinks that this is not the issue of the orbit-db or the example site running it?

**Comment by CSDUMMI** [comment]
I don't know where the issue lies. I would have to try to reproduce it.

**Comment by tabcat** [comment]
I didnt see that it was on the orbitdb example site

**Comment by haydenyoung** [comment]
Closing. I would recommend asking IPFS for support on anything IPFS related.
