### ISSUE TITLE
Should we see the replication times improvement switching from orbitdb 0.26 to 0.28?

### ISSUE THREAD

**Issue by EmiM** [orbitdb/orbitdb#938]
Hello,
we've already asked about it on gitter https://gitter.im/orbitdb/Lobby?at=61a4d643cdb5c1081a3926d3 but I'm creating an issue here because it's easier to find and track.

We recently upgraded orbitdb to 0.28 so currently we use:

```
orbit-db@0.28.0
ipfs@0.60.2 // Because of the fix: https://github.com/ipfs/js-ipfs/issues/3938
libp2p@0.33.0
```

I would expect replication times to go down after that but I don't see much of a difference.

We are running a simple test where one node adds 1000 entries to its local log db, second node connects and replicates this db.
Currently we experience ~20 seconds for localhost p2p network and ~150 seconds for `tor` network (the real life scenario):
https://github.com/ZbayApp/waggle/runs/4326485402?check_suite_focus=true (both 1000 entries).

The times are very similar to what was before:
https://github.com/ZbayApp/waggle/runs/3705573421?check_suite_focus=true

Are the measurements we are getting expected? If not, what should be done to improve them?

**Comment by haydenyoung** [comment]
I would recommend comparing against version 1.
