### ISSUE TITLE
Why keyvalue database can't put buffer as value?

### ISSUE THREAD

**Issue by Paindar** [orbitdb/orbitdb#940]
when i try to put a key-value 

> like:
var value = {
      val: {
        data: [6,4,2,6,5,6,87,87,0,2,32,3,213,54,54,123,234,185,226,55,6,56,67,56,34,32,42,42,91,],
        type: "Buffer",
      }
}
db.put('test.bin', value);

it looks fine. but when i try to read a file(maybe it's not a good idea) and put it as value:

> const imgdata = fs.readFileSync('test.bin');
   db.set(key, {'val':imgdata})

it looks fine too. But if some peer try to get this key, error will occur:

> Error: Could not validate signature "304402...4d42396" for entry "zdpuAt5Pm....bpuzUn" and key "0445d...709" 

i try to read source code to figure out why, but no progress. Could some tell me why?

**Comment by tabcat** [comment]
I'm not sure of the reason but I'd like it to handle any datatype that can be encoded in CBOR which may already be the case; the CBOR codec used should be able to encode Uint8Arrays and Buffers.
However its probably not best to store img data inside the entries and would probably be best to first upload the images to ipfs and store the CID inside the db.

**Comment by Paindar** [comment]
@tabcat  I agree. Its just a trial.
But it looks like this error will cause other peers slow down(or no response for a moment).
i try to pass string like JSON.stringify(imgdata), all the peers work well; but if just replace *JSON.stringify(imgdata)* with *imgdata*, error occur in other peer(s).

**Comment by tabcat** [comment]
It's probable that the data being signed is not the same after being decoded for verification, which results in an invalid signature. It's definitely a bug and should be handled, thanks for opening this.

**Comment by tabcat** [comment]
https://github.com/orbitdb/ipfs-log/blob/2cb68814b98ba15f79a8dcf554f26c1505a5985e/src/entry.js#L30-L59

it looks like what is being encoded into the entry and what is being signed are different.
