### ISSUE TITLE
How to implement a sort or order by?

### ISSUE THREAD

**Issue by awcchungster** [orbitdb/orbitdb#945]
Within a orbit db environment, is there a way to sort by values in a doctor?

A use case would be I have "users" that have a column "points". I want to return the top 10 users by points.

**Comment by eats-alone** [comment]
Assuming you are using the docstore, you can probably use something like this: https://github.com/orbitdb/orbit-db/blob/main/API.md#querymapper

**Comment by eats-alone** [comment]
Plz close this if its no longer applicable
