### ISSUE TITLE
Firebase vs. Orbit-DB (No Orbit DB Add Item Event Listener Function?)

### ISSUE THREAD

**Issue by PiusNyakoojo** [orbitdb/orbitdb#949]
Hello. I'm sorry if this isn't the right place to ask for consulting questions.

But how does Orbit-DB compare to Firebase.

(1) We were using firebase to make a digital currency.
(2) The digital currency has a universal basic income so there is a daemon running on Heroku that periodically adds a universal basic income amount to each account

The application is as simple as adding numbers to accounts when they create transaction objects.

Do you believe Orbit-DB is capable of allowing this functionality?

(1) Can you listen to events like on objects like `db.addEventListener('item-id', () => { console.log('something happened') })`
(2) Can you add an event listener where you can listen to if the data is updated or something like that?

Is anyone available to answer questions through emails?

I know I'm overstaying my welcome by adding more comments -_- but

I really do need help figuring out what OrbitDB is capable of and if it can be a replacement for firebase. Firebase is really expensive and is preventing me from finishing my digital currency with a universal basic income.

https://gitlab.com/ecorp-org/ecoin

**Comment by tabcat** [comment]
OrbitDB should not be used to track currency balances, spends, sends or anything like this. To do that you need consensus and we dont deal with that at all. OrbitDB is good for applications that can be [“coordination-free”](https://arxiv.org/pdf/2012.00472.pdf)   (examples: blog sites, chats, etc), and follows the [local-first software](https://www.inkandswitch.com/local-first/) structure.

come join our community chat if you want to talk more: https://app.element.io/#/room/#orbit-db:matrix.org
