### ISSUE TITLE
serialize and deserialize option for OrbitDB stores.

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbitdb#957]
I'm still sitting at the code I talked about yesterday, trying to rewrite it to deal with the encoding issues.

And I was wondering, if it might be useful to have an option to set `serialize` and `deserialize` functions on a store (specifically for the docstore, but maybe others too).

I imagine the API to look like this:
```js
function serialize(obj) {
   return {
    id: obj.id,
    body: uint8arrays.toString(obj.body, "base64url")
   }
}

function deserialize(obj) {
    return {
        id: obj.id,
        body: uint8arrays.fromString(obj.body, "base64url")
    }
}

const db = await orbitdb.docs("example", { 
      indexBy: "id",
      serialize: serialize,
      deserialize: deserialize,
})

let obj = {
    id: "A",
    body: new Uint8Array([1, 3, 45, 42])
}

await db.put(obj)

db.get("A") // => obj.
```

Here I utilize the `serialize` and `deserialize` functions to seamlessly store `Uint8Arrays` - which are not supported by `dag-cbor` the encoding used for some of OrbitDBs internals. When using the store I deal with the Uint8Arrays but they are stored as base64 encoded strings.

I imagine this feature could also be used to create stores for certain custom objects, converting the OrbitDX encoding automatically into a suitable value for the business logic of an application.

An example of this would be to create a store for a custom class:

```js
class Petition {
    constructor(id, content, author, signatures) {
        this.id = id
        this.content = content
        this.author = author
        this.signatures = signatures
    }
    
    get type() { return "petition" }
    
    sign(id) {
        this.signatures.push(id)  
    }
    
    serialize() {
        return {
            id: this.id,
            content: this.content,
            author: author,
            signatures: signatures,
        }
    }
    
    static deserialize(obj) {
        return new Petition(obj.id, obj.content, obj.author, obj.signatures)
    }
}

const petitionDB = await orbitdb.docs("petitions", {
    indexBy: "id",
    serialize: obj => obj.serialize(),
    deserialize: Petition.deserialize,
})

await petitionDB.put(new Petition("A", "Let's do this", "CSDUMMI", []))

let petition = petitionDB.get("A")

petition.type //  "petition"
```

As you can see, while standard JSON objects are stored on OrbitDB, this complexity is hidden and you can treat entries in the docstore as instances of the `Petition` class - together with all the utility functions that this class implements.

**Comment by tabcat** [comment]
> Here I utilize the serialize and deserialize functions to seamlessly store Uint8Arrays - which are not supported by dag-cbor the encoding used for some of OrbitDBs internals.

Uint8Array are supported by dag-cbor; encoded as byte strings. The better option here is to support dag-cbor, which is valid CBOR (just including a few small rules). I much prefer it to JSON especially for our use cases.

I believe the real issue has to do with serializing the data for digital signatures using JSON and serializing it with DAG-CBOR for storage/replication.

**Comment by CSDUMMI** [comment]
That may very well be true.

But this is a feature request more than anything else and not an issue about the serializing for signatures.

And I'm not yet trying to fix the issue of the serializing for signatures here.

**Comment by tabcat** [comment]
Changing how the data is serialized for signing can't be done yet since its a breaking change. It will be part of the entry version 3 spec and is coming with orbitdb 1.0.

I think special serialization can be handled either outside of the store after reading from the methods, or inside the store if the index and methods need it.  Adding options and splitting up where serialization happens inside the database isnt ideal. In this case CBOR fixes everything here and is a much better way to encode bytes as it would be encoding them base256 vs base64. But until that can be done I'd recommend de/serializing the data yourself beforehand and acting like the store only supports JSON atm.
