### ISSUE TITLE
Automated API documentation using jsdoc

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbitdb#958]
I was about to create a PR to add documentation to the API.md about undocumented properties of the `OrbitDB` object.

But I think that we should think about finally adding proper JSDoc documentation to OrbitDB across all repositories, starting with this repository. 

Because if I continue to add documentation of these kinds of details, API.md will soon become outdated and too large to be comprehensive.

**Comment by haydenyoung** [comment]
API documentation is now generated using github actions and jsdoc.
