### ISSUE TITLE
will immutable database flood storage?

### ISSUE THREAD

**Issue by lonnietc** [orbitdb/orbitdb#970]
Hello,

I am learning more about IPFS and its capabilities but also need a good P2P and highly distributed KV database.

Being immutable then would this not mean that that database will grow to extremely huge sizes and slow down?

Also, I need that the KV data is not just replicated across the network of  nodes but also shards so that the DB can be extremely larger and any single node.

Can you please comment on this?

**Comment by tabcat** [comment]
i would try to split up the database up into smaller databases in a deterministic manor, so their addresses can be known.

**Comment by LucaPanofsky** [comment]
This might be helpful 
![Schermata da 2022-03-05 00-49-23](https://user-images.githubusercontent.com/21056850/156857085-1501a74d-d7c8-42f7-8067-75177ec40d21.png)

Pic taken from the field-manual, chapter 3 p.60 
which you can find here: [https://github.com/orbitdb/field-manual](fieldmanual)

Coming to the database's size instead, I think that you have to find a schema enabling you to split the database into many databases - if possible. However, even in this case you might have a very large and growing number of keys.

Finally, if you do not really need to have all the peers replicating the same huge database, it might be the case that you just need a way to distribute some information (may through a gossip pub?)
