### ISSUE TITLE
Code of the example "Live Demo 1" - https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/

### ISSUE THREAD

**Issue by dodevs** [orbitdb/orbitdb#978]
I'm trying to implement an application using ipfs and orbitdb, but I'm having trouble getting two nodes to connect, I believe this working example can help me.

**Comment by tabcat** [comment]
https://github.com/orbitdb/orbit-db-control-center

i thought the github link on the site would lead to the repo but it leads to the main orbit-db repo.
