### ISSUE TITLE
"ERR_DB_OPEN_FAILED"

### ISSUE THREAD

**Issue by sehuno** [orbitdb/orbitdb#979]
<img width="1422" alt="Screen Shot 2022-03-11 at 5 24 54 PM" src="https://user-images.githubusercontent.com/5646111/157998122-229afb27-0739-4466-89d3-6af5132c1130.png">

Hello,
I created a db before and forgot to pin the files and now I cannot access the database in any way and this is the error that I receive in the console.

This is my code:
![Screen Shot 2022-03-11 at 5 28 04 PM](https://user-images.githubusercontent.com/5646111/157998180-d20042d3-fb1d-4bb9-adf7-97c7e115084b.png)

**Comment by tabcat** [comment]
js-ipfs doesnt currently garbage collect, and the error you see is not behavior seen if the entries were garbage collected.
i dont know the issue here unfortunately and everything given here looks fine.

**Comment by haydenyoung** [comment]
Please test against OrbitDB v1. If the problem persists, feel free to open a new issue.
