### ISSUE TITLE
attempting to read data from keyvalue - empty array returned

### ISSUE THREAD

**Issue by mkrajacic** [orbitdb/orbitdb#983]
Using js-ipfs i managed to start two ipfs nodes in node.js and succesfully replicate a database between them., following the GUIDE.md.

However, when i attempt to read the data from the replicated database on a different device, passing the address of the replicated database to the keyvalue function, and trying to display the result of db.all, what i get is an empty array.

the following is the code which attempts to read the data from the database replicated on a different device:

```
const IPFS = require("ipfs");
const OrbitDB = require("orbit-db");

async function main() {
    const ipfsOptions = {
        repo:'./ipfs',
        config:{
            Adresses:{ 
                Swarm: ["/ip4/0.0.0.0/tcp/4012", "/ip4/127.0.0.1/tcp/4013/ws"],
                API: "/ip4/127.0.0.1/tcp/5012",
                Gateway: "/ip4/127.0.0.1/tcp/9191",
                RPC: "/ip4/127.0.0.1/tcp/4839",
            }
        }
    };
    const ipfs = await IPFS.create(ipfsOptions);

    const orbitdb = await OrbitDB.createInstance(ipfs);
    const db = await orbitdb.keyvalue("/orbitdb/zdpuB1z2vyZcQSfPySzCmgjEbR2jdu8Z6CYLjtoVFk2yC7nvt/em-db");

    await db.load();
    const tutto = db.all;
    console.log(tutto);
}
main();
```

What steps do i need to make in order to get this working? I must admit i've spent a long time digging through other issues and i've seen similar questions, but i wasn't able to clearly understand what i should do.

**Comment by LucaPanofsky** [comment]
the other device has to meet someone (a peer) having an updated version of database otherwise it will correctly think that the database is empty

**Comment by justaluckyguy** [comment]
> 
Could you explain why? So how do I synchronize my data in different device?

**Comment by haydenyoung** [comment]
Please test again with OrbitDB v1 and re-open this issue if you are still experiencing problems.
