### ISSUE TITLE
Are you subject to GDPR/CPRA if you store peer ids?

### ISSUE THREAD

**Issue by mar1n3r0** [orbitdb/orbitdb#990]
Hi guys, I am using orbit-db for a little project  and store all peer ids in a public database. I am wondering how do you treat peer ids legally given that they are public and visible in IPFS Desktop already.

**Comment by LucaPanofsky** [comment]
I think that this issue must be addressed by the policy maker to some extent for, at the moment, the law is very confusing and unfriendly to distributed apps.

To me it seems that by participating to a public network any user implicitly accepts the idea of sharing his/her peerId with the public network. 
Maybe one possible solution is to formalize this implicit agreement into a TOS the end user agrees with when using the appication.

**Comment by mar1n3r0** [comment]
Thank you @LucaPanofsky. Let's keep the discussion open in hope of some official position by Berty as well since they already have their TOS and Privacy policy in place. I think we have to split the topic into two logical sections - one is the public network itself(IPFS) and then the persistence layer(orbit-db). When it comes to the network your advice seems very logical. When it comes to orbit itself I think it's the developer's responsibility to protect the data the best way possible. For now I will take your advice and also store only portions of the peer id encrypted in orbit-db to protect at least what goes through my app.

**Comment by haydenyoung** [comment]
https://discuss.ipfs.tech/t/ipfs-and-gdpr-cpra-compliance/13978.

Without becoming too political, the problem with these laws is that they quickly become out-dated because they are unable to keep up with technological advances. Hence, the confusion.
