### ISSUE TITLE
How sync data between two peers after connection is set?

### ISSUE THREAD

**Issue by zethuman** [orbitdb/orbitdb#995]
Good day!

I have machine A and machine B. 
Machine B connects to machine A and replicates data from the database.
Then, data was written to machine B's local replicated data, but machine A does not know about this data.

How can I replcate back to machine A, when something is changed in machine B?

**Comment by tabcat** [comment]
It should happen automatically. Are you reproducing this behavior on a regular basis?

**Comment by haydenyoung** [comment]
Please test against OrbitDB version 1. If the problem persists, please re-open this issue and provide as much information about the problem as you can.
