### ISSUE TITLE
API Docs correction

### ISSUE THREAD

**Issue by porridgewithraisins** [orbitdb/orbitdb#998]
https://github.com/orbitdb/orbit-db/blob/main/API.md#orbitdbopenaddress-options

The API definition for `orbit.open()` says
>create (boolean): Whether or not to create the database if a valid OrbitDB address is not provided. (Default: false)

And also says
>You can use  orbitdb.feed(address, options) instead of orbitdb.open(address, { type: 'feed', ...options })

However, inspecting the code of `orbit.keyvalue()`
``` js
async keyvalue (address, options = {}) {
    options = Object.assign({ create: true, type: 'keyvalue' }, options)
    return this.open(address, options)
}
```
It seems that it defaults `create` to `true`,  which makes it not equivalent to calling `orbit.open()` with type keyvalue.

Sorry if I misunderstood the docs somehow. I am new to orbit-db, and don't know the underlying concepts well enough yet.

**Comment by porridgewithraisins** [comment]
Ok thanks

**Comment by haydenyoung** [comment]
Store-specific repos have been merged into @orbitdb/core package. See latest [API](https://api.orbitdb.org).
