### ISSUE TITLE
OrbitDB on Android devices

### ISSUE THREAD

**Issue by A-FILALI** [orbitdb/orbitdb#999]
I am trying to use OrbitDB and IPFS on a Node.js application. But I don't know if OrbitDb is supported on Android devices?
I would appreciate if someone can provide me with information about this.

**Comment by julienmalard** [comment]
Hope this isn't too late...OrbitDB is pure JS, so it works on Android (and should work on iOS as well). You can also try to make a PWA.
For native android, the Berty project is interesting (though not quite ready): https://berty.tech/
